import type { CoverageRow, Finding } from "./types";

export const COVERAGE: { generated: string; sources: CoverageRow[] } = {
  generated: "2026-09-15",
  sources: [
    {
      id: "ShahramRahbari",
      kind: "کانال عمومی",
      url: "https://t.me/s/ShahramRahbari",
      earliest: "2018-11-04",
      latest: "2026-09-15",
      inspected: 2001,
      nonempty: 1668,
      usefulSeo: 1016,
      videos: 133,
      qaProxy: 462,
      inaccessible:
        "چند شناسه خالی در بازه 1 تا 2880. ویدئوها پیاده سازی نشدند؛ فقط عنوان و کپشن ماند.",
      note: "2018 تا 2021 بیشتر خبر و بازنشر است. لایه باارزش تجربی 2022 تا 2026 است. 46 یافته استخراج شده از همین پیکره است نه از تمام 1016 پست مفید.",
    },
    {
      id: "TheSEOCommunity",
      kind: "گروه عمومی بدون پیش نمایش",
      url: "https://t.me/TheSEOCommunity",
      earliest: null,
      latest: null,
      inspected: 0,
      nonempty: 0,
      usefulSeo: 0,
      videos: 0,
      qaProxy: 0,
      inaccessible:
        "گروه فقط با عضویت (~3189 عضو). پیش نمایش t.me/s هیچ پیامی نشان نمی دهد. کل تاریخ پرسش و پاسخ پوشش نشده است.",
      note: "تنها وکیل قابل دسترس: پاسخ هایی در کانال شهرام که پرسش را نقل می کنند.",
    },
    {
      id: "mahdi_araqii",
      kind: "کانال عمومی",
      url: "https://t.me/s/mahdi_araqii",
      earliest: "2020-05-04",
      latest: "2025-07-21",
      inspected: 370,
      nonempty: 362,
      usefulSeo: 38,
      videos: 5,
      qaProxy: 8,
      inaccessible: "پنج ویدئو پیاده سازی نشد.",
      note: "اعتماد پیشینی پایین تر. بیشتر تاکتیک و ابزار. فقط به عنوان فرضیه وارد کارخانه می شود مگر شاهد مستقل باشد.",
    },
    {
      id: "MoradiSEOPR",
      kind: "کانال عمومی",
      url: "https://t.me/s/MoradiSEOPR",
      earliest: "2022-05-09",
      latest: "2022-05-09",
      inspected: 35,
      nonempty: 24,
      usefulSeo: 8,
      videos: 19,
      qaProxy: 0,
      inaccessible:
        "نوزده ویدئوی دوره در پیش نمایش «media too big» است. رونوشت در دسترس نیست.",
      note: "یک روز در 2022. عنوان جلسات: استراتژی متن، فاکتورهای محتوا، استخراج تیتر. HISTORICAL_ONLY.",
    },
  ],
};

export const FINDINGS: Finding[] = [
  {
    id: "F-001",
    source: "ShahramRahbari",
    messageId: "2880",
    url: "https://t.me/ShahramRahbari/2880",
    date: "2026-09-15",
    author: "شهرام رهبری",
    topic: "تولید محتوا",
    subtopic: "چک لیست کیفیت",
    claimType: "PRACTICAL_RULE",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "صفحات اطلاعاتی در جستجوی وب گوگل، 2026.",
    observation:
      "پژوهش اصلی، یکدستی کیفیت کل سایت، ارزش افزوده، تازگی، تجربه نمایان، پاسخ در بالا، پرسش های مرتبط، نویسنده مشخص، راستی آزمایی عدد. شمار واژه ضعیف ترین اهرم است. عکس استوک و محتوای اسکیل شده با هوش مصنوعی زیان بارند.",
    normalised: "صفحه وقتی می ماند که واقعیت، تصمیم، یا مشاهده دست اول تازه اضافه کند؛ نه وقتی به سقف کلمه برسد.",
    applicability: "مرکز دانش و صفحات توضیحی خدمات تزویسه.",
    risk: "کم. با سیاست محتوای اسکیل شده گوگل هم راستا است.",
    factory: "بریف باید ارزش افزوده را نام ببرد. قلم می نویسد. بازبینی ویرایشی متن پف کرده را رد می کند.",
    actionability: "now",
  },
  {
    id: "F-002",
    source: "ShahramRahbari",
    messageId: "2877",
    url: "https://t.me/ShahramRahbari/2877",
    date: "2026-09-14",
    author: "شهرام رهبری",
    topic: "نیت جستجو",
    subtopic: "قبل از نوشتن",
    claimType: "CONTENT_STRATEGY",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "نشانی تازه یا بازنویسی.",
    observation:
      "اول نیت جستجو. ربط معنایی کل صفحه. اعتبار موضوعی سایت. عنوان با موضوع یکی. هر بند کامل. H1 اصطلاح اصلی. زبان و مکان. ساختار در زیرعنوان. متا توصیف عامل رتبه نیست. کلیدواژه در نشانی ضعیف است. دامنه تطابق دقیق دیگر کار نمی کند.",
    normalised: "نیت و تمام بودن بند از توکن نشانی و خرافات متا توصیف جلوتر است.",
    applicability: "تمام صفحات پورتفوی پایان نامه.",
    risk: "کم.",
    factory: "صفحه برای جا دادن کلیدواژه در اسلاگ ساخته نمی شود. سیاست نشانی تزویسه بماند؛ دامنه تطابق دقیق تعقیب نشود.",
    actionability: "now",
  },
  {
    id: "F-003",
    source: "ShahramRahbari",
    messageId: "2878",
    url: "https://t.me/ShahramRahbari/2878",
    date: "2026-09-15",
    author: "شهرام رهبری",
    topic: "بک لینک",
    subtopic: "کیفیت پیوند",
    claimType: "LINK_BUILDING_OBSERVATION",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "آف پیج برای سایت جاافتاده.",
    observation:
      "صفحه ارجاعی موضوعی که خودش ترافیک دارد ارجح است. شمار دامنه ارجاعی از شمار خام بک لینک مهم تر است. تمرکز انکر روی عبارت هدف، اما سهم تطابق دقیق بالا به سمت اسپم می رود. نوفالو ضعیف است. DA و PA متریک ابزارند نه عامل گوگل. لینک اسپم صرف نظر از دامنه زیان می زند.",
    normalised: "پیوند کمتر از صفحه ای که کار می کند، نه پیوند بیشتر از دامنه خالی.",
    applicability: "اگر تزویسه رپورتاژ بگیرد؛ دلیل شروع کارزار رپورتاژ نیست.",
    risk: "انکر تطابق دقیق؛ سیاست پیوند پولی.",
    factory: "نقشه انکر خدمات کانونی می ماند. سهم تطابق دقیق بالا نرود. DA شاخص کارخانه نیست.",
    actionability: "queue",
  },
  {
    id: "F-004",
    source: "ShahramRahbari",
    messageId: "2812",
    url: "https://t.me/ShahramRahbari/2812",
    date: "2026-08-26",
    author: "شهرام رهبری",
    topic: "برخورد نیت",
    subtopic: "سازوکار در برابر استعاره",
    claimType: "ALGORITHM_INTERPRETATION",
    stance: "DEPENDS",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "دو یا چند نشانی برای پرس وجوی نزدیک.",
    observation:
      "کنیبالیزیشن را به عنوان سیستم رتبه گوگل رد می کند. سازوکار مستند: تنوع سایت (معمولا حداکثر دو نتیجه از یک سایت) و کانونی سازی نزدیک تکراری. مولر: نشانی اضافه به خودی خود مسئله نیست. ادغام، تمرکز، یا حذف وقتی صفحه لاغر، بی تمرکز، یا بی پیوند است؛ نه چون فولکلور «قدرت را نصف کرد».",
    normalised: "همپوشانی نیت مسئله ویرایش و معماری است، نه اثبات نصف شدن پیج رنک.",
    conflictGroup: "C-CANNIBAL",
    applicability: "مالکیت کانونی در کل پورتفو.",
    risk: "اگر قانون مالکیت رها شود، صفحه مترادف باز منتشر می شود.",
    factory: "یک مالک کانونی برای هر نیت. تشخیص از «کنیبال گوگل» به «برخورد نیت / همپوشانی لاغر» تغییر نام دهد. نشانی برنده را دسته جمعی ادغام نکنید.",
    actionability: "now",
  },
  {
    id: "F-005",
    source: "ShahramRahbari",
    messageId: "2610",
    url: "https://t.me/ShahramRahbari/2610",
    date: "2026-06-13",
    author: "شهرام رهبری",
    topic: "تازه سازی محتوا",
    subtopic: "جوهر در برابر تاریخ",
    claimType: "CASE_STUDY",
    stance: "DO",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "نشانی های موجود در ایندکس. ادعای n=15000. روش مستقل کاملا عمومی نیست.",
    observation:
      "آپدیت جزئی ممکن است رتبه را پایین بیاورد. بازنویسی اصولی با تغییر بیش از حدود 30 درصد محتوا میانگین 5.45 جایگاه ادعا شده. هم راستا با مولر: عوض کردن تاریخ بدون تغییر واقعی اثری ندارد.",
    normalised: "تازه سازی یعنی بازنویسی تصمیم، شاهد، و مثال. تاریخ را به عنوان حقه دست نزنید.",
    result: "ادعای میانگین 5.45 جایگاه پس از بازنویسی بالای 30 درصد؛ ویرایش کوچک ممکن است افت بدهد.",
    conflictGroup: "C-DATES",
    applicability: "راهنماهای در حال افت تزویسه با ایمپرشن، جایگاه 5 تا 20.",
    risk: "بازنویسی افراطی صفحه برنده. رقم 5.45 داده ما نیست.",
    factory: "صف تازه سازی پژوهش: جوهر اول. کار فقط تاریخی ممنوع. همگروه محدود.",
    actionability: "test",
  },
  {
    id: "F-006",
    source: "GoogleOfficial",
    url: "https://developers.google.com/search/docs/essentials/spam-policies",
    date: "2026-08-28",
    author: "Google Search Central",
    topic: "محتوای هوش مصنوعی",
    subtopic: "سوءاستفاده محتوای اسکیل شده",
    claimType: "TECHNICAL_FINDING",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "صفحات زیاد که عمدتا برای دستکاری رتبه ساخته شده اند، با یا بدون هوش مصنوعی.",
    observation:
      "سوءاستفاده محتوای اسکیل شده اسپم رسمی است. هوش مصنوعی مولد یکی از روش های تولید است نه خود جرم. سامانه محتوای مفید مارس 2024 در هسته ادغام شد.",
    normalised: "صفحه مترادف را صنعتی نکنید. هوش مصنوعی فقط وقتی مجاز است که صفحه هنوز به خواننده واقعی کمک کند.",
    conflictGroup: "C-AI",
    applicability: "تمام کارخانه.",
    risk: "ضربه کیفیت کل دامنه.",
    factory: "ایده تلگرام برای نشانی تازه کافی نیست. صفحه های سفته بازانه P4 روی خط تولید نمی آیند.",
    actionability: "now",
  },
  {
    id: "F-007",
    source: "ShahramRahbari",
    messageId: "2821",
    url: "https://t.me/ShahramRahbari/2821",
    date: "2026-08-29",
    author: "شهرام رهبری",
    topic: "سئوی سایت تازه",
    subtopic: "رشد پله ای",
    claimType: "HYPOTHESIS",
    stance: "TEST",
    currency: "NEEDS_REVALIDATION",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "سایت تازه، حدود یک ماه، فقط محتوا و تجربه، بدون لینک. کیس شخصی هنوز باز است.",
    observation:
      "آمار ممکن است تخت بماند تا از آستانه ای بگذرد، بعد جهش کند نه رشد خطی. فورا دنبال باگ نگردید. 2822: سایت را برای کیس استادی ساخته نه برای فروش دوره.",
    normalised: "فلات سایت تازه به خودی خود شکست فنی نیست.",
    result: "آزمایش باز؛ وعده انتشار نتیجه در هر دو حالت.",
    applicability: "فقط دارایی تازه. تزویسه تازه نیست.",
    risk: "صبر بیش از حد روی نقص واقعی خزش یا ایندکس.",
    factory: "این را روی سایت جاافتاده کپی نکنید. اگر دامنه تازه راه افتاد، پنجره 8 تا 12 هفته قبل از حسابرسی هراس ثبت شود.",
    actionability: "queue",
  },
  {
    id: "F-008",
    source: "ShahramRahbari",
    messageId: "769",
    url: "https://t.me/ShahramRahbari/769",
    date: "2022-07-31",
    author: "شهرام رهبری",
    topic: "ایندکس",
    subtopic: "noindex و پیج رنک",
    claimType: "Q_AND_A",
    stance: "DEPENDS",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "پرسش: آیا صفحه نوایندکس هنوز پیج رنک می دهد؟",
    observation:
      "صفحه دارای پیوند داخلی یا خارجی که یک بار خزیده شده، حتی پس از دی ایندکس، ممکن است پیج رنک بدهد. نوایندکس فالو طولانی مدت کم کم نوایندکس نوفالو می شود چون خزش آن نشانی می میرد.",
    normalised: "noindex چاه آنی پیج رنک نیست؛ اگر خزش قطع شود تبدیل می شود.",
    conflictGroup: "C-NOINDEX",
    applicability: "برچسب، ابزار لاغر، نشانی پارامتر.",
    risk: "رها کردن زباله «برای پیج رنک» گراف را آلوده می کند.",
    factory: "نشانی که هنوز هاب است را noindex نکنید. 301 به مالک، بهبود، یا 410 اگر باید بمیرد.",
    actionability: "queue",
  },
  {
    id: "F-009",
    source: "ShahramRahbari",
    messageId: "2276",
    url: "https://t.me/ShahramRahbari/2276",
    date: "2025-08-29",
    author: "شهرام رهبری",
    topic: "خزش",
    subtopic: "robots در برابر noindex",
    claimType: "TECHNICAL_FINDING",
    stance: "DEPENDS",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "نشانی مسدود یا نوایندکس که هنوز پیوند می گیرد.",
    observation:
      "مسدود کردن با robots خزش را قطع می کند نه پیج رنک به نشانی پیوندشده. noindex,follow تا وقتی خزیده شود پیج رنک می دهد. نوفالو از 2019 راهنمایی است. چرخه حدود دو ساله پیج رنک برای هر نشانی هیوریستیک شخصی است نه عدد گوگل.",
    normalised: "برای کشتن یک نشانی به عنوان پیونددهنده، هم خزش و هم پیوند را قطع کنید؛ robots به تنهایی ابزار غلط است.",
    conflictGroup: "C-PR-CYCLE",
    applicability: "سئوی فنی؛ نشانی پارامتر و فیلتر.",
    risk: "قانون پنداشتن چرخه دو ساله.",
    factory: "robots در برابر noindex در برابر 410 در سئوی فنی ثبت شود. چرخه دو ساله TEST / هیوریستیک.",
    actionability: "now",
  },
  {
    id: "F-010",
    source: "ShahramRahbari",
    messageId: "1832",
    url: "https://t.me/ShahramRahbari/1832",
    date: "2024-06-17",
    author: "شهرام رهبری",
    topic: "افسانه های رایج",
    subtopic: "فهرست 2024",
    claimType: "OPINION",
    stance: "DEPENDS",
    currency: "SUPERSEDED",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "فهرست چیزهایی که به گفته او رشد یا افت نمی سازند.",
    observation:
      "در فهرست افسانه: کنیبال کلیدواژه، LSI، DA/PA، دامین ریتینگ، اسپم اسکور، بانس، درگیری، منشن برند، بهینه سازی رنک برین، تراست گوگل، لایک به عنوان رتبه، وحشت لینک سمی، محتوای هوش مصنوعی، آسمان خراش.",
    normalised:
      "متریک ابزار و برچسب فولکلور سامانه گوگل نیستند. چند مورد همین فهرست بعدا توسط خود نویسنده تحدید شد (هوش مصنوعی اسکیل شده زیان بار است؛ همپوشانی نشانی هنوز مالک ویرایشی می خواهد).",
    conflictGroup: "C-AI",
    applicability: "دفتر نپذیرید.",
    risk: "خواندن فهرست 2024 به عنوان سیستم عامل 2026.",
    factory: "DA/PA/LSI/آسمان خراش از Config بیرون بماند. «محتوای هوش مصنوعی» را بی ضرر مطلق ندانید — F-001 و F-006.",
    actionability: "now",
  },
  {
    id: "F-011",
    source: "ShahramRahbari",
    messageId: "2740",
    url: "https://t.me/ShahramRahbari/2740",
    date: "2026-08-02",
    author: "شهرام رهبری",
    topic: "محتوای هوش مصنوعی",
    subtopic: "شکست مشاوره",
    claimType: "FIELD_OBSERVATION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "ده مشاوره اخیر، نیچ نامشخص.",
    observation:
      "از مشتری خواست استراتژی، محتوا، گراف لینک، و رپورتاژ را با هوش مصنوعی ننویسد، رپورتاژ اسپم نخرد، گردش کار محتوا را خودکار نکند، سایت را وایب کد نکند.",
    normalised: "تولید بازبینی نشده با هوش مصنوعی حالت شکستی است که روی پروژه زنده می بیند.",
    conflictGroup: "C-AI",
    applicability: "خط تولید کارخانه.",
    risk: "مسدود کردن پیش نویس مفیدی که هنوز از قلم و بازبینی می گذرد.",
    factory: "پژوهش → بریف → قلم → بازبینی مستقل. هرگز «این پست تلگرام را مقاله کن».",
    actionability: "now",
  },
  {
    id: "F-012",
    source: "ShahramRahbari",
    messageId: "2726",
    url: "https://t.me/ShahramRahbari/2726",
    date: "2026-07-27",
    author: "شهرام رهبری",
    topic: "بک لینک",
    subtopic: "درگیری ساختگی روی رپورتاژ",
    claimType: "OPINION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "نشانی رپورتاژ پولی.",
    observation:
      "کلیک رپورتاژ از چند آی پی و دستگاه، اسکرول، و ورود از گوگل اگر رتبه دارد — برای ارسال سیگنال رتبه و پیج رنک.",
    normalised: "رفتار کاربر ساختگی است. با هشدار بعدی خودش درباره ترافیک جعلی شبیه گوگل برخورد می کند (F-013).",
    conflictGroup: "C-FAKE-TRAFFIC",
    applicability: "هیچ برای تزویسه.",
    risk: "اسپم و دستکاری ترافیک. ریسک سیاست و حقوقی.",
    factory: "نپذیرید. به عنوان تناقض ثبت شود. روی سایت ما آزمایش نشود.",
    actionability: "reject",
  },
  {
    id: "F-013",
    source: "ShahramRahbari",
    messageId: "2874",
    url: "https://t.me/ShahramRahbari/2874",
    date: "2026-09-14",
    author: "شهرام رهبری",
    topic: "شکست سئو",
    subtopic: "ترافیک جعلی شبیه گوگل",
    claimType: "FIELD_OBSERVATION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "سایت با کلیک زیاد روی پرس وجوی تخصصی بدون سرنخ متناظر. چند دارایی یک مالک.",
    observation: "ترافیک جعلی با لباس بازدید گوگل. کلیک بالا به تنهایی تقلب نیست؛ منبع و رفتار داخل سایت را ببینید.",
    normalised: "کلیکی که کنش کسب وکار پرس وجو را نمی سازد مسئله کیفیت ترافیک است نه جام رتبه.",
    conflictGroup: "C-FAKE-TRAFFIC",
    applicability: "سیگنال سئو و گزارش. تبدیل برتر از متریک پوچ.",
    risk: "پرچم زدن کم؛ ساختن زیاد.",
    factory: "سیگنال سئو مشاهده ای می ماند. قبل از جشن کنسول، «سرنخ در برابر کلیک» چک شود.",
    actionability: "now",
  },
  {
    id: "F-014",
    source: "ShahramRahbari",
    messageId: "2655",
    url: "https://t.me/ShahramRahbari/2655",
    date: "2026-06-25",
    author: "شهرام رهبری",
    topic: "جستجوی هوش مصنوعی",
    subtopic: "یادداشت رویداد پاریس",
    claimType: "ALGORITHM_INTERPRETATION",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "AI Overviews / دیسکاور / متریک گزارش در 2026.",
    observation:
      "پرس وجوی فن اوت جا برای منبع بیشتر می سازد. گوگل هوش مصنوعی را برای هوش مصنوعی بودن جریمه نمی کند؛ شلختگی را جریمه می کند. llms.txt و مارک داون ویژه فعلا مزیت ندارند. دیسکاور سیگنال کیفیت سرچ را بازاستفاده می کند. استراتژی را با ایمپرشن و کلیک راه نبرید؛ سلامت کسب وکار سیگنال واقعی است.",
    normalised: "سئوی بنیاد هنوز سطح هوش مصنوعی را تغذیه می کند. پرونده GEO اختراع نکنید. کنسول را نپرستید.",
    applicability: "صفحات دانش تزویسه که ممکن است منبع نقل شوند.",
    risk: "تعقیب llms.txt به عنوان هک رتبه.",
    factory: "وظیفه llms.txt ساخته نشود. کیفیت درخواست مشاوره اندازه گیری شود نه فقط ایمپرشن.",
    actionability: "now",
  },
  {
    id: "F-015",
    source: "ShahramRahbari",
    messageId: "2712",
    url: "https://t.me/ShahramRahbari/2712",
    date: "2026-07-22",
    author: "علیرضا ناجی / کانال",
    topic: "خزش",
    subtopic: "ظرفیت خزش 2026",
    claimType: "TECHNICAL_FINDING",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "سایت بالای ده هزار نشانی، یا «کشف شده هنوز ایندکس نشده» زیاد.",
    observation:
      "گوگل هر سایت را با سقف ظرفیت محافظه کارانه شروع می کند و اگر سرور خوب جواب بدهد بالا می برد. ظرفیت بین خزنده ها مشترک است. تقاضا به اندازه، نرخ به روزرسانی، کیفیت، و پیوند بیرونی بستگی دارد. HTTP 304 توصیه شده. کشف شده ایندکس نشده اغلب یعنی ظرفیت کافی نیست نه جریمه.",
    normalised: "تزویسه سایت میلیون نشانی نیست. بحران بودجه خزش اختراع نکنید. سرور سریع بماند و واریانت نشانی منفجر نشود.",
    applicability: "سئوی فنی. نشانی فیلتر.",
    risk: "خواندن کشف شده ایندکس نشده به عنوان اقدام دستی.",
    factory: "سئوی فنی: 304 ثبت شود، انفجار پارامتر نباشد، «سایت را خاموش کنید تا دوباره بخزد» نیاید.",
    actionability: "queue",
  },
  {
    id: "F-016",
    source: "ShahramRahbari",
    messageId: "2876",
    url: "https://t.me/ShahramRahbari/2876",
    date: "2026-09-14",
    author: "شهرام رهبری",
    topic: "آپدیت گوگل",
    subtopic: "پنجره بازیابی",
    claimType: "FIELD_OBSERVATION",
    stance: "DEPENDS",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "پروژه های قدیمی نامشخص پس از اختلال رتبه.",
    observation: "اثر بیشتر در سطح پرس وجو و صفحه بود تا کل سایت. بازگشت به باند قبلی گاهی بیش از شش ماه طول کشید.",
    normalised: "پس از پنجره هسته یا اسپم انتظار بازیابی یک شبه نداشته باشید. کل سایت را از ترس بازنویسی نکنید.",
    applicability: "اگر تزویسه خوشه ای از پرس وجوها را از دست بدهد.",
    risk: "صبر ابدی روی مسئله اسپم واقعی.",
    factory: "درخت صبر در برابر مداخله: اگر تطابق سیاست اسپم است عمل کنید؛ اگر نوسان هسته است 4 تا 8 هفته همگروه را ببینید.",
    actionability: "queue",
  },
  {
    id: "F-017",
    source: "ShahramRahbari",
    messageId: "2678",
    url: "https://t.me/ShahramRahbari/2678",
    date: "2026-07-07",
    author: "شهرام رهبری",
    topic: "اعتبار موضوعی",
    subtopic: "شعاع سایت / تخصص بخش",
    claimType: "HYPOTHESIS",
    stance: "TEST",
    currency: "NEEDS_REVALIDATION",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "اسناد داخلی درز 2024 به علاوه سه کیس بی نام: یکی کار کرد، یکی ناقص، یکی هیچ. آپدیت فوریه دیسکاور: تخصص در سطح بخش نه فقط کل سایت.",
    observation: "پراکندگی محتوا («شعاع سایت») ممکن است روی رتبه وزن بگذارد. تخصص دیسکاور در سطح بخش است.",
    normalised: "داخل قلمرو موضوعی سایت بمانید. عمودی تصادفی برای «رشد ترافیک» باز نکنید.",
    applicability: "نقشه سایت خواهر. تزویسه پایان نامه و پژوهش می ماند. پزشکی بیرون است.",
    risk: "برازش بیش از حد روی درز.",
    factory: "نمایه سایت برنده است. محتوای پزشکی در این کارخانه نیست. عمودی تازه بدون نمایه باز نشود.",
    actionability: "now",
  },
  {
    id: "F-018",
    source: "ShahramRahbari",
    messageId: "2549",
    url: "https://t.me/ShahramRahbari/2549",
    date: "2025-12-15",
    author: "شهرام رهبری",
    topic: "ایندکس",
    subtopic: "noindex جاوااسکریپت",
    claimType: "TECHNICAL_FINDING",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "صفحه ای که برای برداشتن noindex به جاوااسکریپت تکیه دارد.",
    observation: "اگر noindex در HTML اولیه باشد گوگل ممکن است رندر را رد کند. noindex را در HTML خام نگذارید اگر نشانی باید ایندکس شود.",
    normalised: "قواعد ایندکس باید در نخستین پاسخ HTML زندگی کنند.",
    applicability: "رندر قالب یا اپ.",
    risk: "دی ایندکس تصادفی ابزار یا راهنما.",
    factory: "چک سئوی فنی: noindex پیش فرض روی کانونی های عمومی نباشد.",
    actionability: "queue",
  },
  {
    id: "F-019",
    source: "ShahramRahbari",
    messageId: "2768",
    url: "https://t.me/ShahramRahbari/2768",
    date: "2026-08-08",
    author: "شهرام رهبری",
    topic: "بک لینک",
    subtopic: "موج سوار معقول",
    claimType: "ALGORITHM_INTERPRETATION",
    stance: "DO",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "دو پیوند از یک صفحه به مقصدهای مختلف. پتنت US7716225B1، منقضی 2025، خانواده ادامه دارد.",
    observation:
      "پیوندهای یک صفحه برابر نیستند. موقعیت، متن اطراف، پاپ آپ، شکل نشانی مقصد، و تطابق موضوعی احتمال کلیک موج سوار معقول را عوض می کند. پتنت پیاده سازی امروز نیست.",
    normalised: "پیوند بدنه مقاله مرتبط همان شیء پیوند فوتر صفحه پاپ آپ نیست.",
    applicability: "اگر اصلا آف پیج استفاده شود.",
    risk: "پتنت 2004 را API رتبه 2026 پنداشتن.",
    factory: "اگر منشن به دست آمد، بدنه، تطابق موضوعی، پیوند خروجی کم. دلیل خرید بیشتر نیست.",
    actionability: "queue",
  },
  {
    id: "F-020",
    source: "ShahramRahbari",
    messageId: "2787",
    url: "https://t.me/ShahramRahbari/2787",
    date: "2026-08-20",
    author: "شهرام رهبری",
    topic: "تجربه تخصص اعتبار اعتماد",
    subtopic: "متخصص در برابر مجله در YMYL",
    claimType: "FIELD_OBSERVATION",
    stance: "DO",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "پرس وجوی پزشکی هنگام خرید رپورتاژ داروخانه.",
    observation: "سایت خبری و مجله با وجود برند ضعیف بودند؛ بیمارستان، آزمایشگاه، سایت تخصصی پزشکی بسیاری از نتایج را گرفته بودند.",
    normalised: "در موضوع پرخطر، نهاد متخصص مجله عمومی را می برد. مشاوره پایان نامه پزشکی نیست؛ کارخانه ها مخلوط نشوند.",
    applicability: "تأیید می کند سایت پزشکی بیرون این کارخانه بماند.",
    risk: "هیچ اگر دیوار بماند.",
    factory: "صفحه بالینی روی تزویسه نوشته نشود. نمایانی نویسنده روی صفحات روش پژوهش هنوز مهم است.",
    actionability: "now",
  },
  {
    id: "F-021",
    source: "mahdi_araqii",
    messageId: "425",
    url: "https://t.me/mahdi_araqii/425",
    date: "2024-08-15",
    author: "مهدی عراقی",
    topic: "ایندکس",
    subtopic: "خاموش کردن سایت برای رخزش",
    claimType: "EXPERIMENT",
    stance: "DONT",
    currency: "HISTORICAL_ONLY",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "یک بلاگ، 3 تا 4 ماه تخت حدود 200 کلیک در روز، بدون تغییر محتوا یا لینک، دو روز دان، بعد رخزش. می گوید باگ فنی نبود.",
    observation: "پس از دو روز آفلاین بعضی نشانی ها دوباره خزیده شدند و چند تا به جایگاه یک رسیدند؛ باند ترافیک بالا شکست.",
    normalised: "یک آزمایش کنترل نشده دان شدن کتاب بازیابی نیست. با راهنمای ظرفیت خزش می جنگد.",
    conflictGroup: "C-DOWNTIME",
    applicability: "هیچ.",
    risk: "قطع، اعتماد، سرکوب خزش.",
    factory: "نپذیرید. صف نشود.",
    actionability: "reject",
  },
  {
    id: "F-022",
    source: "mahdi_araqii",
    messageId: "448",
    url: "https://t.me/mahdi_araqii/448",
    date: "2024-12-05",
    author: "مهدی عراقی",
    topic: "شکست سئو",
    subtopic: "پاپ آپ و کلیک جعلی",
    claimType: "Q_AND_A",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "پرسش تکراری شاگرد: پاپ آپ، کلیک جعلی، بگو دوستان سرچ کنند، کپی لینک سایت وایید رقیب، سایت همه چیزگو در برابر متخصص.",
    observation:
      "می گوید تاکتیک غیرطبیعی جعلی است و سیگنال «حذفم کن» می فرستد. هنوز اعتراف می کند روی بعضی رپورتاژ ترافیک انسان نمای جعلی می زند — تناقض دیگر برای ثبت نه کپی.",
    normalised: "پاپ آپ، کلیک جعلی سرپ، و «به دوستان بگو ما را بجو» تاکتیک تزویسه نیستند.",
    conflictGroup: "C-FAKE-TRAFFIC",
    applicability: "نپذیرید.",
    risk: "سامانه اسپم.",
    factory: "رد. پرسش متداول کارخانه: میان بر نیستند.",
    actionability: "reject",
  },
  {
    id: "F-023",
    source: "mahdi_araqii",
    messageId: "444",
    url: "https://t.me/mahdi_araqii/444",
    date: "2024-11-24",
    author: "مهدی عراقی",
    topic: "استراتژی محتوا",
    subtopic: "زنده ماندن پس از آپدیت",
    claimType: "HYPOTHESIS",
    stance: "DEPENDS",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "سایت نامشخص.",
    observation: "ماندن پس از آپدیت با ربط، تجربه کاربری (تکرار)، خوشه، E-E-A-T، لینک داخلی، آف پیج هدفمند — با تجربه کاربری به عنوان همخوان.",
    normalised: "تجربه کاربری و لینک داخلی به عنوان لایه پایدار محتمل و ارزان آزمایش است. پروتکل نیست.",
    applicability: "قالب خدمات و راهنما.",
    risk: "شعار شدن تجربه کاربری.",
    factory: "قواعد تجربه فارسی بماند. لینک داخلی فقط پس از وجود مالک کانونی.",
    actionability: "queue",
  },
  {
    id: "F-024",
    source: "mahdi_araqii",
    messageId: "439",
    url: "https://t.me/mahdi_araqii/439",
    date: "2024-11-23",
    author: "مهدی عراقی",
    topic: "بک لینک",
    subtopic: "تورم DA با ریدایرکت گوگل",
    claimType: "OPINION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "خواستن DA شبیه ماز تا شبکه رپورتاژ دامنه را بپذیرد.",
    observation: "فهرست ریدایرکت google.com/url برای تورم DA/PA؛ بعد می گوید روی سئو اثر ندارد.",
    normalised: "بازی با متریک شخص ثالث برای ورود به بازار رپورتاژ استراتژی رتبه نیست و کار ما نیست.",
    applicability: "هیچ.",
    risk: "خزش تلف شده، احتمال تداعی اسپم.",
    factory: "نپذیرید. DA شاخص کارخانه نیست (F-003، F-010).",
    actionability: "reject",
  },
  {
    id: "F-025",
    source: "mahdi_araqii",
    messageId: "422",
    url: "https://t.me/mahdi_araqii/422",
    date: "2024-08-13",
    author: "مهدی عراقی",
    topic: "بک لینک",
    subtopic: "برچسب ثابت روی رپورتاژ",
    claimType: "HYPOTHESIS",
    stance: "TEST",
    currency: "NEEDS_REVALIDATION",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "رپورتاژ تکراری روی یک ناشر.",
    observation:
      "برچسب نویسنده ثابت که بعد لینک می شود تا رپورتاژ بعدی همان ناشر تقویت شود، زودتر ایندکس شود، و کلیدواژه باقی مانده بردارد.",
    normalised: "نام ثابت نویسنده روی میزبان الگوی نشر واقعی است. ساختن گراف لینک از آن برچسب اثبات نشده و نزدیک سوءاستفاده شهرت سایت است.",
    applicability: "پیش فرض تزویسه نیست.",
    risk: "سوءاستفاده شهرت سایت اگر میزبان پوسته رتبه باشد.",
    factory: "شبکه لینک برچسب ساخته نشود. صفحه نویسنده روی دامنه خودمان مجاز است.",
    actionability: "reject",
  },
  {
    id: "F-026",
    source: "MoradiSEOPR",
    messageId: "24",
    url: "https://t.me/MoradiSEOPR/24",
    date: "2022-05-09",
    author: "دوره مرادی",
    topic: "استراتژی محتوا",
    subtopic: "نقشه دوره",
    claimType: "CONTENT_STRATEGY",
    stance: "DEPENDS",
    currency: "HISTORICAL_ONLY",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "تخلیه دوره با حدود 22 مشترک؛ ویدئو پردازش نشده.",
    observation:
      "عنوان برنامه: استراتژی متن محتوا، فایل نمونه چند مقاله، فاکتورهای محتوا، استخراج تیتر. بدون رونوشت، قاعده عملیاتی از گفتار استخراج نشد.",
    normalised: "برنامه ریزی تیتر و گذر فاکتور محتوا قبل از نوشتن با F-002 سازگار است، اما این منبع تا رونوشت ارتقا نمی یابد.",
    applicability: "شکاف پوشش، نه قاعده کارخانه.",
    risk: "اختراع قاعده از عنوان جلسه.",
    factory: "رسانه پردازش نشده ثبت شود. به عنوان شاهد استناد نشود.",
    actionability: "queue",
  },
  {
    id: "F-027",
    source: "Synthesis",
    date: "2026-09-15",
    author: "سنتز کارخانه",
    topic: "معماری سایت",
    subtopic: "مالک کانونی",
    claimType: "SITE_ARCHITECTURE",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "SITE_DATA_EVIDENCE",
    conditions: "تزویسه و هر سایت خواهر.",
    observation:
      "کارخانه از قبل یک مالک برای هر نیت می خواهد. شهرام می گوید گوگل سامانه کنیبال ندارد اما وقتی همپوشانی توجیه ندارد ادغام، تمرکز، یا حذف را تأیید می کند. سیاست محتوای اسکیل شده گوگل صفحات شبیه را جریمه می کند.",
    normalised: "مالکیت کانونی قانون معماری ما است. به نام فولکلور کنیبال وابسته نیست.",
    conflictGroup: "C-CANNIBAL",
    applicability: "سلسله مراتب و پیوند؛ نقشه انکر خدمات.",
    risk: "کم.",
    factory: "مدل مالکیت عوض نشود. زبان تازه در دستورالعمل: برخورد نیت، نه «گوگل نشانی را خورد».",
    actionability: "now",
  },
  {
    id: "F-028",
    source: "Synthesis",
    date: "2026-09-15",
    author: "سنتز کارخانه",
    topic: "عنوان و نرخ کلیک",
    subtopic: "ایمپرشن بدون کلیک",
    claimType: "SEARCH_CONSOLE_OBSERVATION",
    stance: "TEST",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "ایمپرشن بالا، نرخ کلیک ضعیف، جایگاه حدود 5 تا 15، پرس وجو هنوز با نیت یکی است.",
    observation:
      "اهل فن در این باند اغلب عنوان را عوض می کنند. شهرام 2026 می گوید کل استراتژی را با ایمپرشن و کلیک راه نبرید. گوگل: متا توصیف عامل رتبه نیست اما ممکن است نرخ کلیک را عوض کند.",
    normalised: "آزمایش عنوان آزمایش محدود نرخ کلیک است، نه جادوی رتبه و نه اهرم سراسری.",
    applicability: "نشانی مرکز دانش با داده کنسول.",
    risk: "عنوان برنده را از اصطلاح سر دور کردن.",
    factory: "تب آزمایش سئو: همگروه 8 تا 12 نشانی، پرس وجوی اصلی در H1 بماند، فقط عنوان بازنویسی شود.",
    actionability: "test",
  },
  {
    id: "F-029",
    source: "ShahramRahbari",
    messageId: "2851",
    url: "https://t.me/ShahramRahbari/2851",
    date: "2026-09-07",
    author: "شهرام رهبری / جان مولر",
    topic: "محتوای اسکیل شده",
    subtopic: "صفحه ترکیبی قالبی",
    claimType: "FIELD_OBSERVATION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "ده هزار صفحه ساخته شده با حلقه روی فهرست دامنه × فناوری × ویژگی.",
    observation:
      "مولر: سامانه ها بر اساس صفحه های قدیمی اعتمادشان را به اینکه سایت برای کاربر ارزش می سازد از دست داده اند. فاعل جمله سایت است نه صفحه. صفحه خوب دست نویس هم زیر همان سایه می ماند. درست شدن زمان و تلاش زیاد می برد.",
    normalised: "کیفیت در سطح دامنه از بایگانی قضاوت می شود. صفحه ترکیبی ارزان کل سایت را لکه می کند.",
    conflictGroup: "C-AI",
    applicability: "هر تولید انبوه نشانی، از جمله مترادف خدمات پایان نامه.",
    risk: "بالا اگر کارخانه ترکیب کلیدواژه بسازد.",
    factory: "نشانی ترکیبی («انجام پایان نامه فوری تهران ارزان») ساخته نشود. اگر بایگانی لاغر قالبی هست، هرس قبل از تولید تازه.",
    actionability: "now",
  },
  {
    id: "F-030",
    source: "GoogleOfficial",
    url: "https://t.me/ShahramRahbari/2275",
    date: "2025-08-26",
    author: "Google / کانال شهرام",
    topic: "دامنه منقضی",
    subtopic: "سه سوءاستفاده اسپم 2025",
    claimType: "TECHNICAL_FINDING",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "آپدیت اسپم اوت 2025 و سیاست های جاری اسپم.",
    observation:
      "سه خط مشی رایج: سوءاستفاده دامنه منقضی، محتوای تولید انبوه، سوءاستفاده شهرت سایت. شهرت گذشته دامنه تضمین رتبه محتوای نامرتبط تازه نیست. میزبان معتبر هم اگر محتوای شخص ثالث برای دوشیدن سیگنال رتبه بگذارد متخلف است.",
    normalised: "خرید دامنه پیر برای رتبه گرفتن محتوای بی ربط، و کاشتن محتوا روی سایت معتبر دیگران، سیاست اسپم است نه رشد.",
    conflictGroup: "C-EXPIRED",
    applicability: "تمام پورتفو. تاریخچه دامنه.",
    risk: "اقدام دستی یا افت سیستمی.",
    factory: "دامنه منقضی برای تزویسه نخرید. محتوای شخص ثالث روی دامنه ما برای رتبه کاشته نشود.",
    actionability: "now",
  },
  {
    id: "F-031",
    source: "ShahramRahbari",
    messageId: "280",
    url: "https://t.me/ShahramRahbari/280",
    date: "2020-01-15",
    author: "شهرام رهبری",
    topic: "دامنه منقضی",
    subtopic: "خرید با DA و PA",
    claimType: "OUTDATED_OR_SUPERSEDED",
    stance: "DONT",
    currency: "SUPERSEDED",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "آموزش 2020 درباره حراج دامنه منقضی و 301.",
    observation: "پیشنهاد خرید دامنه منقضی با قدمت، DA/PA بالا، بدون جریمه، سپس 301. فهرست Godaddy و ExpiredDomains.",
    normalised: "توصیه 2020 با سیاست سوءاستفاده دامنه منقضی 2025 باطل شده است. تاریخ بماند.",
    conflictGroup: "C-EXPIRED",
    applicability: "دفتر نپذیرید.",
    risk: "اجرای تاکتیک 2020 روی دارایی 2026.",
    factory: "F-030 بر F-031 مقدم است. در Config نیاید.",
    actionability: "reject",
  },
  {
    id: "F-032",
    source: "ShahramRahbari",
    messageId: "2792",
    url: "https://t.me/ShahramRahbari/2792",
    date: "2026-08-22",
    author: "شهرام رهبری",
    topic: "ریدایرکت و مهاجرت",
    subtopic: "نقشه ریدایرکت حداقل یک سال",
    claimType: "FIELD_OBSERVATION",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "مهاجرت ساختار نشانی. یک پروژه با چند بار تغییر نشانی در چند ماه؛ ریدایرکت هست، رتبه برنمی گردد.",
    observation: "گوگل معمولا ماندن ریدایرکت حداقل یک سال را می خواهد. دستکاری زود نقشه جلوی انتقال سیگنال را می گیرد.",
    normalised: "اسلاگ برنده را برای زیبایی عوض نکنید. اگر مهاجرت شد، نقشه را منجمد کنید.",
    applicability: "هر تغییر نشانی تزویسه.",
    risk: "زنجیره ریدایرکت و از دست رفتن باند رتبه.",
    factory: "اسلاگ خدمات و راهنمای برنده قفل. تداخل /contact/ جدا حل شود نه با رقص نشانی.",
    actionability: "now",
  },
  {
    id: "F-033",
    source: "ShahramRahbari",
    messageId: "1169",
    url: "https://t.me/ShahramRahbari/1169",
    date: "2023-05-21",
    author: "برایان کیسی / کانال",
    topic: "هرس محتوا",
    subtopic: "کیس IBM هشتاد درصد",
    claimType: "CASE_STUDY",
    stance: "DEPENDS",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "برند جهانی با ده ها هزار صفحه، 160 زبان، مدیریت داخلی غیرممکن. 9 ماه ساده سازی.",
    observation: "حذف بیش از 80 درصد محتوا با افزایش ترافیک و NPS همراه شد. انگیزه مدیریت پیچیدگی بود نه ترفند سئو.",
    normalised: "هرس وقتی معماری از انسان و ربات بزرگ تر شده کار می کند. تزویسه IBM نیست.",
    conflictGroup: "C-PRUNE",
    applicability: "فقط همپوشانی لاغر، خارج از قلمرو، یا قالبی. نه راهنمای برنده.",
    risk: "کپی 80 درصد حذف روی سایت کوچک.",
    factory: "هرس انتخابی روی مترادف و زباله. صفحه برنده KEEP.",
    actionability: "queue",
  },
  {
    id: "F-034",
    source: "ShahramRahbari",
    messageId: "2184",
    url: "https://t.me/ShahramRahbari/2184",
    date: "2025-03-19",
    author: "کانال شهرام",
    topic: "ایندکس",
    subtopic: "آستانه اهمیت",
    claimType: "HYPOTHESIS",
    stance: "DEPENDS",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "صفحه ایندکس نمی شود یا بعد از مدتی حذف می شود.",
    observation:
      "توضیح عامیانه «آستانه اهمیت»: کیفیت پایین، تکراری، لینک داخلی ضعیف، تعامل کم. تکراری شامل کپی داخلی و خارجی.",
    normalised: "صفحه تکراری یا بی پیوند شانس ایندکس کمتری دارد. «تعامل» به عنوان عامل ایندکس حدس است نه سند.",
    applicability: "مرکز دانش. ابزار لاغر.",
    risk: "بهینه سازی درگیری جعلی برای ایندکس.",
    factory: "یکتایی و پیوند از هاب خزیده. نرخ درگیری را با کلیک جعلی نخرید.",
    actionability: "queue",
  },
  {
    id: "F-035",
    source: "ShahramRahbari",
    messageId: "1982",
    url: "https://t.me/ShahramRahbari/1982",
    date: "2024-09-25",
    author: "شهرام رهبری",
    topic: "اسکیما",
    subtopic: "ستاره روی مقاله",
    claimType: "PRACTICAL_RULE",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "صفحه Article یا راهنما بدون نقد واقعی محصول.",
    observation:
      "ستاره ریچ ریزالت روی آرتیکل رویکرد موتوراول است، ماهیت صفحه را مخدوش می کند، و نوعی فریب با موجودیت نقدی است که وجود ندارد.",
    normalised: "امتیاز تجمعی ساختگی روی راهنما اسپم نمایش است.",
    applicability: "راهنما و خدمات تزویسه.",
    risk: "ریچ ریزالت گمراه کننده؛ بی اعتمادی نشانه گذاری.",
    factory: "AggregateRating روی راهنما ممنوع مگر نقد واقعی محصول با منبع.",
    actionability: "now",
  },
  {
    id: "F-036",
    source: "ShahramRahbari",
    messageId: "2273",
    url: "https://t.me/ShahramRahbari/2273",
    date: "2025-08-06",
    author: "گری ایلیش / کانال",
    topic: "ایندکس",
    subtopic: "سیگنال ایندکس در برابر رتبه",
    claimType: "TECHNICAL_FINDING",
    stance: "DEPENDS",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "جلسه Google Search Central Live درباره سیگنال ایندکس.",
    observation:
      "سیگنال ایندکس به گفته گوگل: کشور، زبان، HTTPS، Core Web Vitals، لینک فالو، تازگی، عدم نقض اسپم، hreflang. ایندکس نمی کنند: سن دامنه، داده ساختاریافته، سایت مپ به تنهایی، خزش پذیری به تنهایی، سرعت لینک، لینک داخلی منطقی، خوانایی، اعتبار موضوعی، عمق، نیت جستجو، کلیدواژه H1، E-E-A-T. بعضی از اینها ممکن است روی رتبه اثر کنند نه روی ورود به ایندکس.",
    normalised: "اسکیما و E-E-A-T بلیط ایندکس نیستند. HTTPS و سلامت سرور و پیوند فالو و تازگی واقعی نزدیک ترند.",
    conflictGroup: "C-INDEX-SIGNALS",
    applicability: "سئوی فنی و صف ایندکس حذف شده.",
    risk: "انتظار ایندکس از FAQ schema.",
    factory: "اسکیما برای فهم و نمایش است نه برای خریدن ایندکس. صفحه باید اول ارزش مستقل داشته باشد.",
    actionability: "now",
  },
  {
    id: "F-037",
    source: "ShahramRahbari",
    messageId: "2375",
    url: "https://t.me/ShahramRahbari/2375",
    date: "2025-10-16",
    author: "شهرام رهبری",
    topic: "اسکیما",
    subtopic: "اعتبارسنج قبل از ریچ ریزالت",
    claimType: "TECHNICAL_FINDING",
    stance: "DO",
    currency: "CURRENT",
    confidence: "medium",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "نشانه گذاری schema.org روی سایت زنده.",
    observation:
      "کد ممکن است در تست ریچ ریزالت تمیز و در Validator پر هشدار باشد. هشدار گسترده باعث می شود گوگل کل نشانه گذاری را نادیده بگیرد و از استنباط خودش استفاده کند. خطای ریچ ریزالت گاهی طبیعی است؛ هشدار Validator نباید بماند.",
    normalised: "نشانه گذاری شکسته از نبودنش بدتر است چون کل بلوک را بی اعتبار می کند.",
    applicability: "Organization، WebSite، Article، FAQ فقط اگر واقعا پرسش است.",
    risk: "اسکیمای تزئینی پرخطا.",
    factory: "سئوی فنی: Validator بدون هشدار. FAQ ساختگی برای کلمات بیشتر نگذارید.",
    actionability: "queue",
  },
  {
    id: "F-038",
    source: "GoogleOfficial",
    url: "https://developers.google.com/search/docs/crawling-indexing/links-crawlable",
    date: "2023-02-16",
    author: "Google Search Central / کانال 1077",
    topic: "پیوند داخلی",
    subtopic: "بهترین روش انکر",
    claimType: "TECHNICAL_FINDING",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "پیوند خزیدنی داخل محتوا و از سایت های دیگر.",
    observation:
      "سند لینک گوگل: انکر جنریک، انکر خیلی طولانی، و پیوندهای چسبیده به هم بد است. نوفالو فقط وقتی منبع را باور ندارید؛ نه روی هر پیوند خروجی.",
    normalised: "انکر صادق و کوتاه. پیوند از متن. نوفالو را آیین خروج نکنید.",
    applicability: "سلسله مراتب و پیوند؛ نقشه انکر خدمات.",
    risk: "انکر تطابق دقیق در هر بند.",
    factory: "انکر خدمات از نقشه. انکر آموزشی برای راهنما. «اینجا کلیک کنید» و انکر طوماری ممنوع.",
    actionability: "now",
  },
  {
    id: "F-039",
    source: "ShahramRahbari",
    messageId: "690",
    url: "https://t.me/ShahramRahbari/690",
    date: "2022-06-14",
    author: "جان مولر / کانال",
    topic: "ریدایرکت و مهاجرت",
    subtopic: "301 لوله تمام اعتبار نیست",
    claimType: "Q_AND_A",
    stance: "DEPENDS",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "OFFICIAL_EVIDENCE",
    conditions: "پرسش انتقال کامل اعتبار دامنه مبدأ به مقصد با 301.",
    observation:
      "مولر از چارچوب «همه چیز منتقل می شود یا نه» پرهیز می کند. هدف ریدایرکت گفتن به کاربر و خزنده است که نشانی در دسترس نیست. پیوندهای قدیمی مهم را با مقصد تازه به روز کنید.",
    normalised: "301 لوله جادویی DA نیست. کاربر و خزنده را به مالک درست ببرید.",
    applicability: "ادغام تماس، هرس مترادف، مهاجرت قالب.",
    risk: "خرید دامنه و 301 به تزویسه به امید ریختن قدرت.",
    factory: "301 برای برخورد نیت و نشانی مرده. نه برای تزریق اعتبار دامنه منقضی (F-030).",
    actionability: "now",
  },
  {
    id: "F-040",
    source: "ShahramRahbari",
    messageId: "2616",
    url: "https://t.me/ShahramRahbari/2616",
    date: "2026-06-16",
    author: "شهرام رهبری",
    topic: "هرس محتوا",
    subtopic: "هرس مهم تر از تولید؟",
    claimType: "HYPOTHESIS",
    stance: "TEST",
    currency: "NEEDS_REVALIDATION",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "تحلیل کد درز گوگل درباره Page Quality به عنوان امتیاز ریاضی؛ کیس عمومی ضمیمه نشده.",
    observation: "ادعا: هرس از تولید محتوا مهم تر است و نوسان کیفیت سایت باید کنترل شود. شاهد روش جداگانه در پست نیست.",
    normalised: "کنترل نوسان کیفیت دامنه معقول است. «هرس همیشه برتر از نوشتن» قانون نیست.",
    conflictGroup: "C-PRUNE",
    applicability: "سایت با بایگانی لاغر. تزویسه اول همپوشانی را حل کند نه تولید را متوقف.",
    risk: "توقف راهنمای مفید به نام هرس.",
    factory: "هرس فقط با درخت DELETE/301/IMPROVE/KEEP. تولید مترادف متوقف شود؛ تولید نیت تازه مستند نه.",
    actionability: "queue",
  },
  {
    id: "F-041",
    source: "ShahramRahbari",
    messageId: "480",
    url: "https://t.me/ShahramRahbari/480",
    date: "2020-10-14",
    author: "شهرام رهبری",
    topic: "افسانه های رایج",
    subtopic: "چک لیست راه اندازی 2020",
    claimType: "OUTDATED_OR_SUPERSEDED",
    stance: "DONT",
    currency: "SUPERSEDED",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "فهرست بیست بندی راه اندازی سایت، اکتبر 2020.",
    observation:
      "حداقل 800 کلمه، AMP ایده آل، یوآست، عنوان 40 تا 60 «کلمه»، متا 130 تا 150 «کلمه»، لینک داخلی همیشه دوفالو.",
    normalised: "سقف کلمه، AMP اجباری، و طول متا به واحد کلمه منسوخ یا غلط اندازه گیری شده اند. F-001 شمار واژه را ضعیف ترین اهرم می داند.",
    conflictGroup: "C-WORDCOUNT",
    applicability: "دفتر نپذیرید. چند نکته فنی سالم ماند: TTFB، یک نسخه دامنه، H1 یکتا.",
    risk: "پف کردن راهنما تا 800 کلمه.",
    factory: "حد کلمه در بریف نباشد. AMP پیش فرض نیست.",
    actionability: "reject",
  },
  {
    id: "F-042",
    source: "mahdi_araqii",
    messageId: "434",
    url: "https://t.me/mahdi_araqii/434",
    date: "2024-09-16",
    author: "مهدی عراقی",
    topic: "عنوان و نرخ کلیک",
    subtopic: "تاریخ در اسنیپت",
    claimType: "Q_AND_A",
    stance: "TEST",
    currency: "CURRENT_BUT_CONTEXTUAL",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "مقاله دو ساله که قبلا خط 1 تا 3 بوده، بعد افت. تاریخ در اسنیپت نمایان.",
    observation: "حدس می زند کاربر تاریخ کهنه را می بیند و کلیک نمی کند. راه حل تلویحی توجه به تاریخ نشر.",
    normalised: "تاریخ نمایان ممکن است نرخ کلیک را بزند. دستکاری تاریخ بدون جوهر همان C-DATES است.",
    conflictGroup: "C-DATES",
    applicability: "راهنمای کهنه با اسنیپت تاریخ دار.",
    risk: "تاریخ ساختگی برای تازه به نظر آمدن.",
    factory: "اگر تاریخ اسنیپت مسئله است، جوهر را بازنویسی کنید تا تاریخ صادق عوض شود. تاریخ را در قالب دروغ نگویید.",
    actionability: "test",
  },
  {
    id: "F-043",
    source: "mahdi_araqii",
    messageId: "442",
    url: "https://t.me/mahdi_araqii/442",
    date: "2024-11-24",
    author: "مهدی عراقی",
    topic: "بک لینک",
    subtopic: "مانی ربات و منشن",
    claimType: "OPINION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "تورم DA برای پذیرش در پلتفرم رپورتاژ.",
    observation: "مانی ربات برای منشن نشانی در وب 2 تا خزش ماز DA را تا 30-34 بالا ببرد.",
    normalised: "منشن خودکار برای فریب متریک شخص ثالث ساخت لینک نیست و در کارخانه نمی آید.",
    applicability: "هیچ.",
    risk: "گراف لینک اسپم.",
    factory: "نپذیرید. در کنار F-024.",
    actionability: "reject",
  },
  {
    id: "F-044",
    source: "mahdi_araqii",
    messageId: "457",
    url: "https://t.me/mahdi_araqii/457",
    date: "2025-03-09",
    author: "مهدی عراقی",
    topic: "شکست سئو",
    subtopic: "رفرش خودکار پربازدیدها",
    claimType: "OPINION",
    stance: "DONT",
    currency: "CURRENT",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "سایدبار «پربازدیدترین» که با هر رفرش مرتب می شود.",
    observation: "افزونه رفرش خودکار برای نشستن رپورتاژ در بلوک پربازدید و گرفتن لینک داخلی از همه صفحات.",
    normalised: "جعل محبوبیت برای لینک سایت وایید دستکاری است.",
    applicability: "هیچ.",
    risk: "لینک سایت وایید ساختگی؛ نشانه گذاری اسپم.",
    factory: "نپذیرید. لینک داخلی تزویسه از هاب واقعی و متن است نه از شمارنده تقلبی.",
    actionability: "reject",
  },
  {
    id: "F-045",
    source: "ShahramRahbari",
    messageId: "452",
    url: "https://t.me/ShahramRahbari/452",
    date: "2020-08-28",
    author: "شهرام رهبری",
    topic: "شکست سئو",
    subtopic: "ربودن لینک مهمان",
    claimType: "OUTDATED_OR_SUPERSEDED",
    stance: "DONT",
    currency: "HISTORICAL_ONLY",
    confidence: "low",
    evidenceKind: "FIELD_EVIDENCE",
    conditions: "آموزش 2020 درباره جایگزینی مقصد لینک رپورتاژ یا ویرگول؛ حتی سئوی منفی.",
    observation: "تکنیک ربودن مقصد لینک پست مهمان و اشاره به کاربرد سئوی منفی.",
    normalised: "ربودن پیوند و سئوی منفی در کارخانه نیست، حتی به عنوان تاریخ.",
    applicability: "دفتر نپذیرید.",
    risk: "سوءاستفاده و تلافی.",
    factory: "رد. محتوای پزشکی و سئوی منفی مخلوط نشود.",
    actionability: "reject",
  },
  {
    id: "F-046",
    source: "Synthesis",
    date: "2026-09-15",
    author: "سنتز کارخانه",
    topic: "خدمات در برابر بلاگ",
    subtopic: "دیوار نیت تجاری",
    claimType: "SITE_ARCHITECTURE",
    stance: "DO",
    currency: "CURRENT",
    confidence: "high",
    evidenceKind: "SITE_DATA_EVIDENCE",
    conditions: "تزویسه: خدمات /thesis/ /proposal/ /service-statistics/ /service-simulation/ /service-project/ و مرکز دانش /blog/.",
    observation:
      "نیت تجاری باید روی نشانی خدمات بماند. راهنما نیت را آموزش می دهد و به مالک خدمات با انکر صادق پیوند می دهد. مقاله بلاگ برای «مشاوره انجام پایان نامه» ساخته نمی شود.",
    normalised: "بلاگ مالک نیت معاملاتی نمی شود. خدمات مالک راهنمای فصل نمی شود.",
    applicability: "نقشه انکر خدمات؛ صف ویرایش.",
    risk: "دو نشانی برای یک نیت تجاری.",
    factory: "نقشه انکر دست نخورد مگر شاهد معماری. راهنما فقط انکر آموزشی یا بخشی به خدمات.",
    actionability: "now",
  },
];
