import type { CalculatorChild, OsGap, Technique, ValidationCheck } from "./types";

/** Living closeout. A gap is either fixed here, queued with owner, accepted, or blocked. */
export const OS_GAPS: OsGap[] = [
  {
    id: "G-01",
    area: "هویت سازمان",
    gap: "نام حقوقی و نشانی در صفحات عمومی نیست. تلفن و ایمیل روی /contact-us/ دیده شد.",
    disposition: "queued",
    owner: "A-11 / POL-ABOUT",
    next: "هویت واقعی را از Maziyar بگیریم. اینجا اختراع نمی شود.",
  },
  {
    id: "G-02",
    area: "حریم",
    gap: "نشانی /privacy-policy/ عنوان دارد اما متن سیاست در این بازبینی استخراج نشد. فرم inquiry فایل می گیرد.",
    disposition: "queued",
    owner: "A-18 / POL-PRIVACY",
    next: "متن واقعی سیاست؛ کپی مترادف خدمات نه.",
  },
  {
    id: "G-03",
    area: "نویسنده",
    gap: "راهنماها نویسنده و بازبین نمایان ندارند.",
    disposition: "queued",
    owner: "A-12 / C-METHODS / C-STATS",
    next: "جایگاه خالی بماند تا فرد واقعی با رضایت وارد شود.",
  },
  {
    id: "G-04",
    area: "تماس",
    gap: "/contact-us/ روش های تماس است؛ /inquiry/ فرم است؛ /contact/ همان عنوان تماس را نشان داد — احتمالاً همزاد.",
    disposition: "queued",
    owner: "A-17",
    next: "اگر /contact/ همزاد است 301 به /contact-us/. نقش ها را قاطی نکنید.",
  },
  {
    id: "G-05",
    area: "ماشین حساب ها",
    gap: "هاب بیش از هجده ابزار فرزند دارد. حجم نمونه روش دارد. بقیه ممیزی کامل نشده.",
    disposition: "queued",
    owner: "A-16 / PA-TOOLS-HUB",
    next: "ابزار تازه بدون روش، فرض، حد، نسخه نسازید. الگوی کوکران را کپی قالبی نکنید.",
  },
  {
    id: "G-06",
    area: "GSC_AI",
    gap: "دسترسی به دارایی سرچ کنسول در این جعبه ابزار نیست.",
    disposition: "blocked",
    owner: "A-13",
    next: "وقتی گزارش هست، جدا از GSC_WEB ذخیره شود. تا آن روز MONITOR.",
  },
  {
    id: "G-07",
    area: "گروه تلگرام",
    gap: "TheSEOCommunity فقط با عضویت؛ تاریخ پرسش و پاسخ پوشش نشده.",
    disposition: "accepted",
    owner: "coverage",
    next: "شکاف پوشش ثبت شده. وکیل: پرسش های نقل شده در کانال شهرام.",
  },
  {
    id: "G-08",
    area: "ویدئو مرادی",
    gap: "نوزده ویدئو رونوشت ندارند.",
    disposition: "accepted",
    owner: "coverage",
    next: "HISTORICAL_ONLY. قانون عملی از گفتار استخراج نشد.",
  },
  {
    id: "G-09",
    area: "سایت خواهر",
    gap: "نقشه دامنه های مرتبط در این جعبه ابزار نبود.",
    disposition: "accepted",
    owner: "SITES",
    next: "اختراع نشود.",
  },
  {
    id: "G-10",
    area: "انتشار زنده",
    gap: "هیچ نشانی teznevise.ir در این مأموریت بازنویسی نشد.",
    disposition: "accepted",
    owner: "کارخانه",
    next: "صف اقدام برای انسان. پیش نمایش ابزار است نه استقرار.",
  },
  {
    id: "G-11",
    area: "رجیستری نقش",
    gap: "جایگاه خالی به عمد.",
    disposition: "fixed_here",
    owner: "/factory/trust",
    next: "نام جعلی نگذارید.",
  },
  {
    id: "G-12",
    area: "ابزار تصمیم",
    gap: "انتخاب آزمون، امکان سنجی، پرسشنامه، چک لیست دفاع در این جعبه ابزار دمو شده اند.",
    disposition: "fixed_here",
    owner: "/tools",
    next: "تا بازبین آمار منصوب نشود برند «دکتر» نگذارید.",
  },
  {
    id: "G-13",
    area: "پژوهش بیرونی",
    gap: "خوشه رویداد و ضد نویز ساخته شد. متن کامل مقاله ذخیره نمی شود.",
    disposition: "fixed_here",
    owner: "/factory/intel",
    next: "تیتر صنعت وارد تولید نمی شود.",
  },
  {
    id: "G-14",
    area: "نمره E-E-A-T",
    gap: "درصد اعتماد ساخته نشد.",
    disposition: "accepted",
    owner: "R-16",
    next: "شاهد بسازید نه امتیاز.",
  },
  {
    id: "G-15",
    area: "شکاف پژوهش دو URL",
    gap: "shakaf-ha و research-gap همان روز بدون نویسنده.",
    disposition: "queued",
    owner: "A-14",
    next: "اگر تمایز رشته ای واقعی نیست ادغام. پرس وجو را قبل از 301 دسته جمعی ببینید.",
  },
  {
    id: "G-16",
    area: "برش زبان",
    gap: "برش های B و C و G و پیکره نویسندگان نام دار در این بسته ضمیمه نبود.",
    disposition: "accepted",
    owner: "writing-os",
    next: "جعل نشود. پرسش دانشجو از برش D به عنوان زبان خواننده کافی است تا فایل برسد.",
  },
  {
    id: "G-17",
    area: "Ada",
    gap: "فاز ۱: طرح، رسید، قرنطینه، گذرنامه در پیش نمایش. pgvector و استنتاج نیست.",
    disposition: "fixed_here",
    owner: "/ada",
    next: "HMAC تولید جدا. انتشار زنده نه.",
  },
];

export const ORIGINAL_VALUE_KINDS = [
  { id: "observation", label: "مشاهده دست اول" },
  { id: "synthesis", label: "سنتز اصلی" },
  { id: "decision", label: "مدل تصمیم" },
  { id: "calculator", label: "ماشین حساب با روش" },
  { id: "diagnostic", label: "ابزار تشخیص" },
  { id: "comparison", label: "مقایسه اصلی" },
  { id: "recurring", label: "مسئله تکراری ناشناس" },
  { id: "worked", label: "مثال کارشده" },
  { id: "experiment", label: "آزمایش واقعی" },
  { id: "checklist", label: "چک لیست یکتا" },
  { id: "download", label: "فایل قابل ذخیره" },
  { id: "dataset", label: "مجموعه داده" },
  { id: "interpretation", label: "تفسیر متخصص" },
  { id: "iran", label: "بافت دانشگاه ایران" },
  { id: "university", label: "مقایسه آیین نامه دانشگاه" },
  { id: "visual", label: "توضیح تصویری مفید" },
  { id: "workflow", label: "گردش کار تعاملی" },
];

export const TECHNIQUES: Technique[] = [
  {
    id: "TECH-REGIONAL",
    name: "واحد تجمیع گر / ویژگی منطقه ای سرپ",
    claimedMechanism: "اسناد 8 سپتامبر 2026 تفاوت منطقه ای واحدها و کاروسل را توضیح می دهد.",
    evidence: "PRIMARY: aggregator-features. تغییر چیدمان است نه آپدیت رتبه.",
    risk: "ساخت صفحه برای واحدی که در ایران وجود ندارد.",
    sites: "teznevise.ir مخاطب ایران است.",
    testDesign: "آزمایش نمی شود.",
    rollback: "—",
    window: "—",
    status: "ignore",
  },
  {
    id: "TECH-LLMS",
    name: "llms.txt برای رتبه یا AI Overview",
    claimedMechanism: "فایل متنی برای مدل ها.",
    evidence: "سند AI features: فایل ویژه لازم نیست. F-014.",
    risk: "پروژه نمایشی بدون اثر.",
    sites: "همه",
    testDesign: "آزمایش نمی شود.",
    rollback: "—",
    window: "—",
    status: "ignore",
  },
  {
    id: "TECH-FANOUT",
    name: "یک URL برای هر fan-out",
    claimedMechanism: "پوشش پرسش های مشتق هوش مصنوعی.",
    evidence: "سیاست محتوای اسکیل شده. PF-02.",
    risk: "اسپم کیفیت دامنه.",
    sites: "teznevise.ir",
    testDesign: "آزمایش نمی شود.",
    rollback: "—",
    window: "—",
    status: "ignore",
  },
];

export const CALCULATOR_CHILDREN: CalculatorChild[] = [
  {
    id: "CALC-SAMPLE",
    title: "حجم نمونه کوکران",
    url: "https://teznevise.ir/online-calculation-tools/sample-size-calculator/",
    job: "حجم نمونه را با فرض صریح برآورد کنم نه با یک عدد جدول.",
    methodologySeen: "yes",
    action: "SURGICAL_UPDATE",
    note: "فرمول کوکران و مقایسه با مورگان و حد طرح پیچیده در متن است. نسخه و بازبین نیست.",
  },
  {
    id: "CALC-T",
    title: "آزمون t",
    url: "https://teznevise.ir/online-calculation-tools/t-test-calculator/",
    job: "t مستقل، زوجی، یا تک نمونه را کنترل اولیه کنم.",
    methodologySeen: "thin",
    action: "EVIDENCE_REFRESH",
    note: "در این بازبینی متن روش کامل بار نشد.",
  },
  {
    id: "CALC-COHEN",
    title: "کوهن d و هجز g",
    url: "https://teznevise.ir/online-calculation-tools/cohen-d-hedges-g-calculator/",
    job: "اندازه اثر دو گروه مستقل.",
    methodologySeen: "thin",
    action: "EVIDENCE_REFRESH",
    note: "ادعا روی هاب: انحراف معیار تجمیعی و تصحیح هجز. صفحه فرزند جدا ممیزی شود.",
  },
  {
    id: "CALC-ALPHA",
    title: "آلفای کرونباخ",
    url: "https://teznevise.ir/online-calculation-tools/cronbachs-alpha-calculator/",
    job: "پایایی درونی گویه ها.",
    methodologySeen: "unseen",
    action: "EVIDENCE_REFRESH",
    note: "هاب فقط عنوان. حد تفسیر آلفا باید در متن باشد.",
  },
  {
    id: "CALC-META",
    title: "فراتحلیل مقدماتی",
    url: "https://teznevise.ir/online-calculation-tools/meta-analysis-calculator/",
    job: "اثر ثابت و تصادفی DL از اندازه اثر و خطا.",
    methodologySeen: "thin",
    action: "SURGICAL_UPDATE",
    note: "خطر استفاده به جای فراتحلیل کامل. حد باید درشت باشد.",
  },
];

export const VALIDATION: ValidationCheck[] = [
  {
    id: "V-GUIDE",
    requirement: "یک راهنمای اطلاعاتی",
    page: "راهنمای فصل سوم",
    url: "https://teznevise.ir/thesis-third-chapter-guide/",
    lang: "fa",
    role: "RESEARCH_GUIDE",
    task: "partial — فهرست بخش ها کار نوشتن را شروع می کند اما مثال کارشده نیست",
    trust: "who/how missing؛ نویسنده نیست",
    a11y: "فهرست مطالب؛ lang زنده تأیید کامل نشد",
    schema: "Person نگذارید",
    result: "partial",
  },
  {
    id: "V-SERVICE",
    requirement: "یک صفحه خدمات",
    page: "تحلیل آماری",
    url: "https://teznevise.ir/service-statistics/",
    lang: "fa",
    role: "SERVICE",
    task: "yes — محدوده، فایل، حد دستکاری روشن است",
    trust: "how adequate؛ حریم فایل جدا نیست",
    a11y: "جدول باید HTML باشد",
    schema: "ستاره ممنوع",
    result: "partial",
  },
  {
    id: "V-TOOL",
    requirement: "یک ابزار تعاملی",
    page: "انتخاب آزمون",
    url: "/tools/stat-test",
    lang: "fa",
    role: "TOOL",
    task: "yes — درخت با حد",
    trust: "روش و حد در صفحه؛ بازبین unassigned",
    a11y: "fieldset و جدول خزیدنی",
    schema: "در این دامنه نه",
    result: "pass",
  },
  {
    id: "V-DOWNLOAD",
    requirement: "یک دانلود",
    page: "آمادگی دفاع",
    url: "/tools/defence",
    lang: "fa",
    role: "DOWNLOAD",
    task: "yes — فهرست قابل ذخیره",
    trust: "منشأ تحریریه؛ آیین نامه دانشگاه واحد نیست",
    a11y: "چک باکس برچسب دار",
    schema: "نه",
    result: "pass",
  },
  {
    id: "V-EN",
    requirement: "یک صفحه انگلیسی",
    page: "Research briefing",
    url: "/factory/briefing",
    lang: "en",
    role: "RESEARCH_GUIDE",
    task: "yes — what changed / ignore",
    trust: "منبع اولیه حاکم است",
    a11y: "lang=en dir=ltr",
    schema: "نه",
    result: "pass",
  },
  {
    id: "V-FA",
    requirement: "یک صفحه فارسی",
    page: "امکان سنجی موضوع",
    url: "/tools/feasibility",
    lang: "fa",
    role: "TOOL",
    task: "yes — پرچم خطر نه نمره",
    trust: "جای استاد را نمی گیرد",
    a11y: "فرم کیبورد",
    schema: "نه",
    result: "pass",
  },
  {
    id: "V-FP",
    requirement: "یک صفحه با شاهد دست اول",
    page: "حجم نمونه کوکران (زنده)",
    url: "https://teznevise.ir/online-calculation-tools/sample-size-calculator/",
    lang: "fa",
    role: "TOOL",
    task: "partial — مقایسه کوکران و مورگان ارزش است؛ نسخه نیست",
    trust: "روش مرئی؛ بازبین نیست",
    a11y: "skip link روی صفحه زنده دیده شد",
    schema: "نامشخص",
    result: "partial",
  },
];

export const DELIVERABLE = {
  gaps: [
    "هویت حقوقی ناقص؛ حریم پوسته؛ نویسنده خالی؛ دو URL شکاف؛ مزرعه ماشین حساب نیم ممیزی؛ GSC_AI بدون دسترسی.",
    "تماس زنده: /contact-us/ روش ها، /inquiry/ فرم، /contact/ همزاد محتمل.",
  ],
  infrastructure: [
    "رجیستری نقش، نقش صفحه، سیاست، ریست اسکیما، ممیزی URL، سطوح UX، دسترسی، ابزار تصمیم، تجربه دست اول، پژوهش بیرونی، درگاه ارزش افزوده، رجیستر شکاف.",
  ],
  eeat: ["خانه، خدمات، راهنماهای دانش، فرم inquiry. آمار از بقیه how قوی تر است."],
  original: ["فصل سوم کالایی است. شکاف پژوهش تا مثال رشته ای. ماشین حساب ها اگر روش نداشته باشند قالب اند."],
  ux: ["CTA مبهم شروع کنید. موفقیت فرم. چت نباید پاپ اجباری شود."],
  interactive: [
    "دمو: انتخاب آزمون، امکان سنجی، پرسشنامه، چک لیست دفاع. زنده: حجم نمونه الگوی روش.",
  ],
  a11y: ["اینجا: skip، 404، فوکوس، برچسب ابزار. زنده: lang/dir و فرم inquiry در صف."],
  media: ["درخت آزمون و مسیر thesis. اسکرین SPSS با alt. تصویر استوک نه."],
  schema: ["FAQ برای ریچ ریزالت نه. Person بدون فرد نه. ستاره نه."],
  aiMeasure: ["GSC_AI جدا. GEO فروشنده قاطی نشود. fan-out URL نه."],
  factory: ["تب اعتماد، صفحات، تجربه، پژوهش، وضعیت، دریافت تجربه. قلم دست نخورده."],
  notDone: [
    "نمره E-E-A-T، کارشناس جعلی، llms.txt، API کنسول، انتشار زنده، پاپ، حداقل واژه، پرامپت موازی نگارش، متن کامل SEJ، پزشکی، سایت خواهر ساختگی.",
  ],
  blockers: [
    "نام حقوقی واقعی، بازبین نام دار، دسترسی GSC، متن حریم، ممیزی باقی ماشین حساب ها، تاریخ گروه تلگرام.",
  ],
};

export const OS_STATE = {
  label: "سامانه در حال کار است",
  meaning:
    "شکاف ماده یا اینجا بسته شده، یا با مالک در صف است، یا آگاهانه پذیرفته شده، یا پشت دسترسی بیرونی مانده. کارخانه کامل به معنای سایت زنده بازنویسی شده نیست.",
  asOf: "2026-09-16",
};
