import type { A11yFinding, ExperienceNote, InteractiveAsset, UxSurface } from "./types";

export const UX_SURFACES: UxSurface[] = [
  {
    id: "UX-CTA-INQUIRY",
    surface: "دکمه خدمات",
    bad: "شروع کنید / مشاوره رایگان",
    better: "بررسی اولیه پژوهش",
    why: "بازدیدکننده باید بفهمد بعد از کلیک چه می شود.",
  },
  {
    id: "UX-CTA-TOOL",
    surface: "ابزار آزمون",
    bad: "شروع کنید",
    better: "پیشنهاد آزمون را ببینید",
    why: "خروجی درخت است نه ثبت نام.",
  },
  {
    id: "UX-EMPTY-SEARCH",
    surface: "جستجوی مرکز دانش",
    bad: "نتیجه ای یافت نشد.",
    better: "این عبارت راهنمایی در مرکز دانش ندارد. مسیر خدمات یا فرم بررسی را ببینید.",
    why: "صفر نتیجه باید راه بعدی بدهد.",
  },
  {
    id: "UX-404",
    surface: "صفحه پیدا نشد",
    bad: "404 Not Found",
    better: "این صفحه در کارگاه نیست. میز ویرایش، کارخانه، یا خانه را امتحان کنید.",
    why: "fa-IR؛ کار بعدی.",
  },
  {
    id: "UX-FORM-ERROR",
    surface: "خطای فرم",
    bad: "مقدار نامعتبر است",
    better: "نوع مقیاس متغیر وابسته را انتخاب کنید.",
    why: "خطا فیلد را نام می برد.",
  },
  {
    id: "UX-SUCCESS",
    surface: "موفقیت ارسال",
    bad: "موفق",
    better: "درخواست ثبت شد. برای بررسی اولیه فایل داده لازم نیست همین الان کامل باشد.",
    why: "بعد چه می شود.",
  },
  {
    id: "UX-LOADING",
    surface: "بارگذاری",
    bad: "لطفا صبر کنید...",
    better: "پیشنهاد آزمون در حال محاسبه است.",
    why: "محتوا نه انیمیشن تنها.",
  },
  {
    id: "UX-CHAT",
    surface: "چت زنده",
    bad: "پاپ اجباری، شمارش معکوس، اعلان جعلی اپراتور",
    better: "اگر هست، اختیاری و پس از اسکرول؛ خاموشی آسان",
    why: "تعامل باید کار را جلو ببرد. R-18.",
  },
];

export const A11Y: A11yFinding[] = [
  {
    id: "A11Y-01",
    where: "Qalam پوسته",
    issue: "پیوند پرش به محتوا نبود.",
    fix: "پیوند «رفتن به محتوا» در همین نسخه.",
    status: "fixed_here",
  },
  {
    id: "A11Y-02",
    where: "Qalam خطا و 404",
    issue: "خطای چارچوب انگلیسی/زینک بود و 404 نبود.",
    fix: "404 فارسی و خطای هماهنگ با کاغذ/مرکب.",
    status: "fixed_here",
  },
  {
    id: "A11Y-03",
    where: "teznevise.ir",
    issue: "lang/dir، برچسب فرم inquiry، و alt در این بازبینی کامل تأیید نشد.",
    fix: "ممیزی دستی HTML زنده؛ هدف لمسی ≥44px؛ خطا کنار فیلد.",
    status: "queued_for_site",
  },
  {
    id: "A11Y-04",
    where: "ابزارها",
    issue: "خروجی فقط در حالت تعاملی کافی نیست.",
    fix: "جدول/فهرست خزیدنی زیر ویجت.",
    status: "fixed_here",
  },
  {
    id: "A11Y-05",
    where: "راهنماهای تزنویسه",
    issue: "اطلاعات مهم نباید فقط در تصویر منو یا هاور باشد.",
    fix: "مسیر منو و حد عددی در متن.",
    status: "queued_for_site",
  },
];

export const INTERACTIVE_ASSETS: InteractiveAsset[] = [
  {
    id: "IA-STAT",
    name: "انتخاب آزمون آماری",
    userJob: "کدام آزمون آماری را باید در نظر بگیرم؟",
    inputs: ["هدف تحلیل", "مقیاس وابسته", "استقلال مشاهده", "آمادگی مفروضات پارامتری"],
    outputs: ["آزمون نامزد", "مفروضات", "آنچه نیست", "گام بعدی", "حد"],
    methodology: "درخت آموزشی استاندارد آزمون های پایه (t، واریانس، همبستگی، رگرسیون، خی دو و ناپارامتری معادل). جایگزینی برای طراحی پژوهش نیست.",
    evidence: "کتاب های روش؛ نه داده داخلی تزنویسه. آستانه p یا حجم نمونه تجویز نمی شود.",
    limitations:
      "طرح آشیانه، اندازه گیری مکرر پیچیده، بقای، چندسطحی، و داده شمارشی پیشرفته خارج است. نرم افزار روش نیست. بازبین آمار هنوز unassigned است.",
    canonicalOwner: "https://teznevise.ir/service-statistics/",
    fallback: "جدول همان درخت در HTML زیر فرم.",
    a11y: "fieldset، label، کیبورد، بدون هاور. خروجی متن انتخاب شدنی.",
    analytics: ["tool_started", "tool_completed", "useful_yes", "useful_no"],
    maintenanceOwner: "C-STATS (خالی) / کارخانه تا انتصاب",
    lastVerification: "2026-09-16",
    demoPath: "/tools/stat-test",
    status: "demoed_here",
  },
  {
    id: "IA-DEFENCE",
    name: "چک لیست آمادگی دفاع",
    userJob: "قبل از دفاع چه فایل و چه آمادگی کم دارم؟",
    inputs: ["موارد پرونده، اسلاید، داده، صداقت، پرسش داور"],
    outputs: ["فهرست ناقص ها", "فایل متنی قابل ذخیره"],
    methodology: "موارد تکراری مسیر تا دفاع. دانشگاه واحد نیست.",
    evidence: "مشاهده تحریریه ناشناس — نه پرونده دانشجو.",
    limitations: "آیین نامه دانشگاه شما ممکن است موارد اضافه بخواهد.",
    canonicalOwner: "مسیر تا دفاع — مالک URL روی دامنه هنوز قفل نشده",
    fallback: "فهرست کامل بدون جاوااسکریپت در همان صفحه.",
    a11y: "چک باکس برچسب دار؛ درصد پیشرفت متنی.",
    analytics: ["checklist_toggle", "checklist_saved"],
    maintenanceOwner: "کارخانه",
    lastVerification: "2026-09-16",
    demoPath: "/tools/defence",
    status: "demoed_here",
  },
  {
    id: "IA-FEASIBILITY",
    name: "امکان سنجی موضوع",
    userJob: "آیا این موضوع پژوهش در زمان من شدنی است؟",
    inputs: ["دسترسی داده", "مهارت روش", "زمان تا دفاع", "تجهیز", "اخلاق"],
    outputs: ["پرچم خطر", "سؤال برای استاد"],
    methodology: "غربال منابع و زمان. نمره امکان ساختگی نمی دهد.",
    evidence: "منطق تصمیم آموزشی. داده پرونده نیست.",
    limitations: "بدون استاد راهنما تصمیم نهایی نیست.",
    canonicalOwner: "راهنمای انتخاب موضوع وقتی مالک روشن است",
    fallback: "پرسش های غربال در متن.",
    a11y: "فرم استاندارد.",
    analytics: ["feasibility_completed"],
    maintenanceOwner: "C-METHODS",
    lastVerification: "2026-09-16",
    demoPath: "/tools/feasibility",
    status: "demoed_here",
  },
  {
    id: "IA-QUESTIONNAIRE",
    name: "غربال پرسشنامه",
    userJob: "چه چیزی در پرسشنامه ام غلط است؟",
    inputs: ["سازه", "گویه هدایت گر", "مقیاس", "معکوس", "پیش آزمون", "ترجمه", "طول", "اخلاق"],
    outputs: ["پرچم ایست یا خطر", "کار بعدی"],
    methodology: "نقص های رایج طراحی مقیاس در مشاوره. نمره روایی نمی دهد.",
    evidence: "مشاهده تحریریه ناشناس.",
    limitations: "روایی سازه، تحلیل عاملی، و هنجاریابی بیرون است.",
    canonicalOwner: "راهنمای ابزار اندازه گیری وقتی مالک روشن است",
    fallback: "همان هشت پرسش در جدول.",
    a11y: "radiogroup برچسب دار.",
    analytics: ["questionnaire_completed", "useful_yes", "useful_no"],
    maintenanceOwner: "C-METHODS",
    lastVerification: "2026-09-16",
    demoPath: "/tools/questionnaire",
    status: "demoed_here",
  },
];

export const FEEDBACK_EVENTS = [
  { id: "useful_yes", meaning: "صفحه یا ابزار کار را جلو برد", source: "PRODUCT_UX" },
  { id: "useful_no", meaning: "کار حل نشد", source: "PRODUCT_UX" },
  { id: "reason_unclear", meaning: "زبان یا گام مبهم بود", source: "PRODUCT_UX" },
  { id: "reason_wrong_test", meaning: "پیشنهاد آزمون نامربوط بود", source: "PRODUCT_UX" },
  { id: "reason_need_human", meaning: "به مشاور انسان نیاز است", source: "PRODUCT_UX" },
  { id: "tool_completed", meaning: "خروجی دیده شد", source: "PRODUCT_UX" },
  { id: "form_abandoned", meaning: "inquiry نیمه رها شد", source: "GA4" },
];

export const EXPERIENCE_NOTES: ExperienceNote[] = [
  {
    id: "XP-01",
    kind: "FIRST_PARTY_OBSERVATION",
    topic: "نیت تماس",
    observation: "خانه زنده 2026-09-16 به /inquiry/ می رود. ممیزی قبلی /contact/ و /contact-us/ را همپوشان دیده بود. باید زنده 200 بودن قدیمی ها چک شود.",
    cannotPromoteTo: "قانون 301 بدون سر وضعیت.",
    factory: "O-01 با وضعیت NEEDS_LIVE_CHECK.",
    date: "2026-09-16",
  },
  {
    id: "XP-02",
    kind: "FIRST_PARTY_OBSERVATION",
    topic: "نویسنده نمایان",
    observation: "نمونه مرکز دانش (فصل سوم، شکاف، EFA) نویسنده، بازبین، و منبع خارجی ندارد.",
    cannotPromoteTo: "قانون «همه صفحات باید نویسنده داشته باشند» بدون فرد واقعی.",
    factory: "رجیستری نقش خالی نگه داشته شد. نام جعلی نگذارید.",
    date: "2026-09-16",
  },
  {
    id: "XP-03",
    kind: "EDITORIAL_INTERPRETATION",
    topic: "ارزش افزوده خدمات آمار",
    observation: "/service-statistics/ از خانه و thesis برای how قوی تر است: مفروضات، اندازه اثر، حد دستکاری.",
    cannotPromoteTo: "این که همه خدمات کامل اند.",
    factory: "الگوی how برای thesis/proposal.",
    date: "2026-09-16",
  },
  {
    id: "XP-04",
    kind: "ANECDOTE",
    topic: "تازه سازی دسته ای",
    observation: "تاریخ های بلاگ در یک باند کوتاه شهریور ۱۴۰۵ جمع شده اند.",
    cannotPromoteTo: "اثبات تئاتر تاریخ. ممکن است نشر واقعی دسته ای باشد.",
    factory: "اگر GSC افت بعد از دستکاری تاریخ نشان داد، C-DATES. تا آن موقع مشاهده.",
    date: "2026-09-16",
  },
  {
    id: "XP-05",
    kind: "FIRST_PARTY_EXPERIMENT",
    topic: "EX-01 تا EX-03",
    observation: "آزمایش ها هنوز روی سایت وایید نشده اند. فرضیه اند.",
    cannotPromoteTo: "نتیجه بازنویسی 5.45 جایگاه شهرام.",
    factory: "صف آزمایش دست نخورده.",
    date: "2026-09-16",
  },
  {
    id: "XP-06",
    kind: "FIRST_PARTY_OBSERVATION",
    topic: "تماس زنده",
    observation:
      "/contact-us/ تلفن، ایمیل، واتساپ و ساعات دارد. /inquiry/ فرم است. باز کردن /contact/ همان عنوان تماس را نشان داد — همزاد محتمل. خانه هنوز CTA را به inquiry می برد.",
    cannotPromoteTo: "یک مالک تماس برای هر دو کار. روش تماس و فرم دو نیت اند اگر محتوا فرق دارد.",
    factory: "A-17. O-01 به 301 همزاد محدود شود نه حذف /contact-us/.",
    date: "2026-09-16",
  },
  {
    id: "XP-07",
    kind: "FIRST_PARTY_OBSERVATION",
    topic: "مزرعه ماشین حساب",
    observation:
      "هاب بیش از هجده فرزند دارد. حجم نمونه کوکران روش، فرض، و حد طرح پیچیده دارد. این الگو است نه مجوز تولید قالب تازه.",
    cannotPromoteTo: "همه ماشین حساب ها باکیفیت اند. یا باید ماشین حساب بیشتر بسازیم.",
    factory: "A-16. ارزش افزوده = روش مرئی. فرزند بدون how صف EVIDENCE_REFRESH.",
    date: "2026-09-16",
  },
  {
    id: "XP-08",
    kind: "FIRST_PARTY_OBSERVATION",
    topic: "حریم",
    observation: "/privacy-policy/ عنوان سیاست دارد اما متن در این بازبینی استخراج نشد.",
    cannotPromoteTo: "نبود کامل. ممکن است متن پشت اسکریپت باشد — هنوز برای انسان کنار فرم کافی نیست.",
    factory: "POL-PRIVACY exists_weak. A-18.",
    date: "2026-09-16",
  },
];

export const PERFORMANCE_RULES = [
  "LCP، INP، CLS را برای قابلیت استفاده ببینید نه برای نمره کامل.",
  "ویجت تصمیم نباید LCP را با اسکریپت سنگین خراب کند.",
  "اطلاعات مهم در HTML اول باشد.",
  "فرم inquiry خطای ارسال را گم نکند.",
];

export const MULTIMEDIA_GAPS = [
  {
    url: "https://teznevise.ir/service-statistics/",
    opportunity: "نمودار درخت آزمون با متن جایگزین و همان داده در جدول.",
    not: "ویدئوی استوک «تحلیلگر در لپ تاپ».",
  },
  {
    url: "https://teznevise.ir/efa-payan-namayeh-rahnegah-gambe-gam/",
    opportunity: "اسکرین منوی SPSS با alt مسیر دقیق.",
    not: "اینفوگرافیک تزئینی بدون عدد.",
  },
  {
    url: "https://teznevise.ir/thesis/",
    opportunity: "نمودار مسیر همکاری مرحله ای.",
    not: "ویدئوی فروش بدون رونوشت.",
  },
];
