/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaRouteImport } from './routes/ada'
import { Route as AlgorithmRouteImport } from './routes/algorithm'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as RegistersRouteImport } from './routes/registers'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as FactoryIndexRouteImport } from './routes/factory/index'
import { Route as FactoryBriefingRouteImport } from './routes/factory/briefing'
import { Route as FactoryConflictsRouteImport } from './routes/factory/conflicts'
import { Route as FactoryCorpusRouteImport } from './routes/factory/corpus'
import { Route as FactoryIntakeRouteImport } from './routes/factory/intake'
import { Route as FactoryIntelRouteImport } from './routes/factory/intel'
import { Route as FactoryNotebookRouteImport } from './routes/factory/notebook'
import { Route as FactoryOsRouteImport } from './routes/factory/os'
import { Route as FactoryPagesRouteImport } from './routes/factory/pages'
import { Route as FactoryQueueRouteImport } from './routes/factory/queue'
import { Route as FactoryTrustRouteImport } from './routes/factory/trust'
import { Route as FactoryUxRouteImport } from './routes/factory/ux'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsDefenceRouteImport } from './routes/tools/defence'
import { Route as ToolsFeasibilityRouteImport } from './routes/tools/feasibility'
import { Route as ToolsQuestionnaireRouteImport } from './routes/tools/questionnaire'
import { Route as ToolsStatTestRouteImport } from './routes/tools/stat-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaRoute = AdaRouteImport.update({
  id: '/ada',
  path: '/ada',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmRoute = AlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersRoute = RegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryIndexRoute = FactoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryBriefingRoute = FactoryBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryConflictsRoute = FactoryConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryCorpusRoute = FactoryCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryIntakeRoute = FactoryIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryIntelRoute = FactoryIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryNotebookRoute = FactoryNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryOsRoute = FactoryOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryPagesRoute = FactoryPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryQueueRoute = FactoryQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryTrustRoute = FactoryTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => FactoryRoute,
} as any)
const FactoryUxRoute = FactoryUxRouteImport.update({
  id: '/ux',
  path: '/ux',
  getParentRoute: () => FactoryRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDefenceRoute = ToolsDefenceRouteImport.update({
  id: '/defence',
  path: '/defence',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFeasibilityRoute = ToolsFeasibilityRouteImport.update({
  id: '/feasibility',
  path: '/feasibility',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsQuestionnaireRoute = ToolsQuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsStatTestRoute = ToolsStatTestRouteImport.update({
  id: '/stat-test',
  path: '/stat-test',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ada': typeof AdaRoute
  '/algorithm': typeof AlgorithmRoute
  '/bible': typeof BibleRoute
  '/corpus': typeof CorpusRoute
  '/desk': typeof DeskRoute
  '/factory': typeof FactoryRouteWithChildren
  '/patterns': typeof PatternsRoute
  '/registers': typeof RegistersRoute
  '/tools': typeof ToolsRouteWithChildren
  '/factory/briefing': typeof FactoryBriefingRoute
  '/factory/conflicts': typeof FactoryConflictsRoute
  '/factory/corpus': typeof FactoryCorpusRoute
  '/factory/intake': typeof FactoryIntakeRoute
  '/factory/intel': typeof FactoryIntelRoute
  '/factory/notebook': typeof FactoryNotebookRoute
  '/factory/os': typeof FactoryOsRoute
  '/factory/pages': typeof FactoryPagesRoute
  '/factory/queue': typeof FactoryQueueRoute
  '/factory/trust': typeof FactoryTrustRoute
  '/factory/ux': typeof FactoryUxRoute
  '/tools/defence': typeof ToolsDefenceRoute
  '/tools/feasibility': typeof ToolsFeasibilityRoute
  '/tools/questionnaire': typeof ToolsQuestionnaireRoute
  '/tools/stat-test': typeof ToolsStatTestRoute
  '/factory/': typeof FactoryIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ada': typeof AdaRoute
  '/algorithm': typeof AlgorithmRoute
  '/bible': typeof BibleRoute
  '/corpus': typeof CorpusRoute
  '/desk': typeof DeskRoute
  '/patterns': typeof PatternsRoute
  '/registers': typeof RegistersRoute
  '/factory/briefing': typeof FactoryBriefingRoute
  '/factory/conflicts': typeof FactoryConflictsRoute
  '/factory/corpus': typeof FactoryCorpusRoute
  '/factory/intake': typeof FactoryIntakeRoute
  '/factory/intel': typeof FactoryIntelRoute
  '/factory/notebook': typeof FactoryNotebookRoute
  '/factory/os': typeof FactoryOsRoute
  '/factory/pages': typeof FactoryPagesRoute
  '/factory/queue': typeof FactoryQueueRoute
  '/factory/trust': typeof FactoryTrustRoute
  '/factory/ux': typeof FactoryUxRoute
  '/tools/defence': typeof ToolsDefenceRoute
  '/tools/feasibility': typeof ToolsFeasibilityRoute
  '/tools/questionnaire': typeof ToolsQuestionnaireRoute
  '/tools/stat-test': typeof ToolsStatTestRoute
  '/factory': typeof FactoryIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ada': typeof AdaRoute
  '/algorithm': typeof AlgorithmRoute
  '/bible': typeof BibleRoute
  '/corpus': typeof CorpusRoute
  '/desk': typeof DeskRoute
  '/factory': typeof FactoryRouteWithChildren
  '/patterns': typeof PatternsRoute
  '/registers': typeof RegistersRoute
  '/tools': typeof ToolsRouteWithChildren
  '/factory/briefing': typeof FactoryBriefingRoute
  '/factory/conflicts': typeof FactoryConflictsRoute
  '/factory/corpus': typeof FactoryCorpusRoute
  '/factory/intake': typeof FactoryIntakeRoute
  '/factory/intel': typeof FactoryIntelRoute
  '/factory/notebook': typeof FactoryNotebookRoute
  '/factory/os': typeof FactoryOsRoute
  '/factory/pages': typeof FactoryPagesRoute
  '/factory/queue': typeof FactoryQueueRoute
  '/factory/trust': typeof FactoryTrustRoute
  '/factory/ux': typeof FactoryUxRoute
  '/tools/defence': typeof ToolsDefenceRoute
  '/tools/feasibility': typeof ToolsFeasibilityRoute
  '/tools/questionnaire': typeof ToolsQuestionnaireRoute
  '/tools/stat-test': typeof ToolsStatTestRoute
  '/factory/': typeof FactoryIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ada'
    | '/algorithm'
    | '/bible'
    | '/corpus'
    | '/desk'
    | '/factory'
    | '/patterns'
    | '/registers'
    | '/tools'
    | '/factory/briefing'
    | '/factory/conflicts'
    | '/factory/corpus'
    | '/factory/intake'
    | '/factory/intel'
    | '/factory/notebook'
    | '/factory/os'
    | '/factory/pages'
    | '/factory/queue'
    | '/factory/trust'
    | '/factory/ux'
    | '/tools/defence'
    | '/tools/feasibility'
    | '/tools/questionnaire'
    | '/tools/stat-test'
    | '/factory/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ada'
    | '/algorithm'
    | '/bible'
    | '/corpus'
    | '/desk'
    | '/patterns'
    | '/registers'
    | '/factory/briefing'
    | '/factory/conflicts'
    | '/factory/corpus'
    | '/factory/intake'
    | '/factory/intel'
    | '/factory/notebook'
    | '/factory/os'
    | '/factory/pages'
    | '/factory/queue'
    | '/factory/trust'
    | '/factory/ux'
    | '/tools/defence'
    | '/tools/feasibility'
    | '/tools/questionnaire'
    | '/tools/stat-test'
    | '/factory'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/ada'
    | '/algorithm'
    | '/bible'
    | '/corpus'
    | '/desk'
    | '/factory'
    | '/patterns'
    | '/registers'
    | '/tools'
    | '/factory/briefing'
    | '/factory/conflicts'
    | '/factory/corpus'
    | '/factory/intake'
    | '/factory/intel'
    | '/factory/notebook'
    | '/factory/os'
    | '/factory/pages'
    | '/factory/queue'
    | '/factory/trust'
    | '/factory/ux'
    | '/tools/defence'
    | '/tools/feasibility'
    | '/tools/questionnaire'
    | '/tools/stat-test'
    | '/factory/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaRoute: typeof AdaRoute
  AlgorithmRoute: typeof AlgorithmRoute
  BibleRoute: typeof BibleRoute
  CorpusRoute: typeof CorpusRoute
  DeskRoute: typeof DeskRoute
  FactoryRoute: typeof FactoryRouteWithChildren
  PatternsRoute: typeof PatternsRoute
  RegistersRoute: typeof RegistersRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ada': {
      id: '/ada'
      path: '/ada'
      fullPath: '/ada'
      preLoaderRoute: typeof AdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithm': {
      id: '/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof AlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers': {
      id: '/registers'
      path: '/registers'
      fullPath: '/registers'
      preLoaderRoute: typeof RegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory/': {
      id: '/factory/'
      path: '/'
      fullPath: '/factory/'
      preLoaderRoute: typeof FactoryIndexRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/briefing': {
      id: '/factory/briefing'
      path: '/briefing'
      fullPath: '/factory/briefing'
      preLoaderRoute: typeof FactoryBriefingRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/conflicts': {
      id: '/factory/conflicts'
      path: '/conflicts'
      fullPath: '/factory/conflicts'
      preLoaderRoute: typeof FactoryConflictsRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/corpus': {
      id: '/factory/corpus'
      path: '/corpus'
      fullPath: '/factory/corpus'
      preLoaderRoute: typeof FactoryCorpusRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/intake': {
      id: '/factory/intake'
      path: '/intake'
      fullPath: '/factory/intake'
      preLoaderRoute: typeof FactoryIntakeRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/intel': {
      id: '/factory/intel'
      path: '/intel'
      fullPath: '/factory/intel'
      preLoaderRoute: typeof FactoryIntelRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/notebook': {
      id: '/factory/notebook'
      path: '/notebook'
      fullPath: '/factory/notebook'
      preLoaderRoute: typeof FactoryNotebookRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/os': {
      id: '/factory/os'
      path: '/os'
      fullPath: '/factory/os'
      preLoaderRoute: typeof FactoryOsRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/pages': {
      id: '/factory/pages'
      path: '/pages'
      fullPath: '/factory/pages'
      preLoaderRoute: typeof FactoryPagesRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/queue': {
      id: '/factory/queue'
      path: '/queue'
      fullPath: '/factory/queue'
      preLoaderRoute: typeof FactoryQueueRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/trust': {
      id: '/factory/trust'
      path: '/trust'
      fullPath: '/factory/trust'
      preLoaderRoute: typeof FactoryTrustRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/factory/ux': {
      id: '/factory/ux'
      path: '/ux'
      fullPath: '/factory/ux'
      preLoaderRoute: typeof FactoryUxRouteImport
      parentRoute: typeof FactoryRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/defence': {
      id: '/tools/defence'
      path: '/defence'
      fullPath: '/tools/defence'
      preLoaderRoute: typeof ToolsDefenceRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/feasibility': {
      id: '/tools/feasibility'
      path: '/feasibility'
      fullPath: '/tools/feasibility'
      preLoaderRoute: typeof ToolsFeasibilityRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/questionnaire': {
      id: '/tools/questionnaire'
      path: '/questionnaire'
      fullPath: '/tools/questionnaire'
      preLoaderRoute: typeof ToolsQuestionnaireRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/stat-test': {
      id: '/tools/stat-test'
      path: '/stat-test'
      fullPath: '/tools/stat-test'
      preLoaderRoute: typeof ToolsStatTestRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface FactoryRouteChildren {
  FactoryBriefingRoute: typeof FactoryBriefingRoute
  FactoryConflictsRoute: typeof FactoryConflictsRoute
  FactoryCorpusRoute: typeof FactoryCorpusRoute
  FactoryIntakeRoute: typeof FactoryIntakeRoute
  FactoryIntelRoute: typeof FactoryIntelRoute
  FactoryNotebookRoute: typeof FactoryNotebookRoute
  FactoryOsRoute: typeof FactoryOsRoute
  FactoryPagesRoute: typeof FactoryPagesRoute
  FactoryQueueRoute: typeof FactoryQueueRoute
  FactoryTrustRoute: typeof FactoryTrustRoute
  FactoryUxRoute: typeof FactoryUxRoute
  FactoryIndexRoute: typeof FactoryIndexRoute
}

const FactoryRouteChildren: FactoryRouteChildren = {
  FactoryBriefingRoute: FactoryBriefingRoute,
  FactoryConflictsRoute: FactoryConflictsRoute,
  FactoryCorpusRoute: FactoryCorpusRoute,
  FactoryIntakeRoute: FactoryIntakeRoute,
  FactoryIntelRoute: FactoryIntelRoute,
  FactoryNotebookRoute: FactoryNotebookRoute,
  FactoryOsRoute: FactoryOsRoute,
  FactoryPagesRoute: FactoryPagesRoute,
  FactoryQueueRoute: FactoryQueueRoute,
  FactoryTrustRoute: FactoryTrustRoute,
  FactoryUxRoute: FactoryUxRoute,
  FactoryIndexRoute: FactoryIndexRoute,
}

const FactoryRouteWithChildren =
  FactoryRoute._addFileChildren(FactoryRouteChildren)

interface ToolsRouteChildren {
  ToolsDefenceRoute: typeof ToolsDefenceRoute
  ToolsFeasibilityRoute: typeof ToolsFeasibilityRoute
  ToolsQuestionnaireRoute: typeof ToolsQuestionnaireRoute
  ToolsStatTestRoute: typeof ToolsStatTestRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsDefenceRoute: ToolsDefenceRoute,
  ToolsFeasibilityRoute: ToolsFeasibilityRoute,
  ToolsQuestionnaireRoute: ToolsQuestionnaireRoute,
  ToolsStatTestRoute: ToolsStatTestRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaRoute: AdaRoute,
  AlgorithmRoute: AlgorithmRoute,
  BibleRoute: BibleRoute,
  CorpusRoute: CorpusRoute,
  DeskRoute: DeskRoute,
  FactoryRoute: FactoryRouteWithChildren,
  PatternsRoute: PatternsRoute,
  RegistersRoute: RegistersRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
